UPDATE 
    FAI_FARMACO
SET 
    OID=OID
    ?newIsDeleted?
    ?newCodMinsan? 
    ?newCodEan?
    ?newDescrProd?
    ?newAnagrafica?
    ?newDescrTipoProd?
    ?newDescrEstesaTipoProd?
WHERE  
1=1
    ?oldOid? 
    ?oldIsDeleted? 
    ?oldCodMinsan?
	?oldCodEan?
	?oldDescrProd?
	?oldAnagrafica?
	?oldDescrTipoProd?
	?oldDescrEstesaTipoProd?