INSERT INTO FAI_RECORD_D_RESET (OID,OID_FORNITORE,CODICE_CLIENTE,CREATION_TS,UPDATE_TS) VALUES (OID.NEXTVAL,?OID_FORNITORE?,?CODICE_CLIENTE?,SYSDATE,SYSDATE)
DELETE FROM FAI_RECORD_V_RAGGR_COND WHERE OID_FORNITORE=?OID_FORNITORE?
DELETE FROM FAI_RECORD_R_RAGGR_COND WHERE OID_FORNITORE=?OID_FORNITORE?
DELETE FROM FAI_RECORD_A_ADDEBITO_FINANZ WHERE OID_FORNITORE=?OID_FORNITORE?
DELETE FROM FAI_RECORD_C_CONDIZIONI WHERE OID_FORNITORE=?OID_FORNITORE?
DELETE FROM FAI_RECORD_L_LISTINO WHERE OID_FORNITORE=?OID_FORNITORE?