MERGE INTO FAI_RECORD_V_RAGGR_COND tgt
USING
(
SELECT
   ?OID_FORNITORE?             OID_FORNITORE
  ,?AZIONE?                    AZIONE
  ,?CODICE_ADDEBITO?           CODICE_ADDEBITO
  ,?CODICE_CLIENTE?            CODICE_CLIENTE
  ,SYSDATE                     CREATION_TS
  ,?DESCR_ADDEBITO?            DESCR_ADDEBITO
  ,?DESTINAZIONE_ADDEBITO?     DESTINAZIONE_ADDEBITO
  ,?IMORTO_MASSIMO_DA_ADDEB?   IMORTO_MASSIMO_DA_ADDEB
  ,?IMPORTO_DA_ADDEB?          IMPORTO_DA_ADDEB
  ,?NUMERO_MASSIMO_ADDEB?      NUMERO_MASSIMO_ADDEB
  ,?PERC_ADDEB_SU_IMPONIBILE?  PERC_ADDEB_SU_IMPONIBILE
  ,?PERIODICITA_FATTURAZ?      PERIODICITA_FATTURAZ
  ,SYSDATE                     UPDATE_TS
FROM DUAL
) src
ON (tgt.OID_FORNITORE=src.OID_FORNITORE AND tgt.CODICE_CLIENTE=src.CODICE_CLIENTE)
WHEN MATCHED
THEN UPDATE SET
   tgt.AZIONE                   = src.AZIONE
  ,tgt.CODICE_ADDEBITO          = src.CODICE_ADDEBITO
  ,tgt.DESCR_ADDEBITO           = src.DESCR_ADDEBITO
  ,tgt.DESTINAZIONE_ADDEBITO    = src.DESTINAZIONE_ADDEBITO
  ,tgt.IMORTO_MASSIMO_DA_ADDEB  = src.IMORTO_MASSIMO_DA_ADDEB
  ,tgt.IMPORTO_DA_ADDEB         = src.IMPORTO_DA_ADDEB
  ,tgt.NUMERO_MASSIMO_ADDEB     = src.NUMERO_MASSIMO_ADDEB
  ,tgt.PERC_ADDEB_SU_IMPONIBILE = src.PERC_ADDEB_SU_IMPONIBILE
  ,tgt.PERIODICITA_FATTURAZ     = src.PERIODICITA_FATTURAZ
  ,tgt.UPDATE_TS                = src.UPDATE_TS
WHEN NOT MATCHED
THEN INSERT
(
   OID
  ,OID_FORNITORE
  ,AZIONE
  ,CODICE_ADDEBITO
  ,CODICE_CLIENTE
  ,CREATION_TS
  ,DESCR_ADDEBITO
  ,DESTINAZIONE_ADDEBITO
  ,IMORTO_MASSIMO_DA_ADDEB
  ,IMPORTO_DA_ADDEB
  ,NUMERO_MASSIMO_ADDEB
  ,PERC_ADDEB_SU_IMPONIBILE
  ,PERIODICITA_FATTURAZ
  ,UPDATE_TS
)
VALUES
(
   OID.NEXTVAL
  ,src.OID_FORNITORE
  ,src.AZIONE
  ,src.CODICE_ADDEBITO
  ,src.CODICE_CLIENTE
  ,src.CREATION_TS
  ,src.DESCR_ADDEBITO
  ,src.DESTINAZIONE_ADDEBITO
  ,src.IMORTO_MASSIMO_DA_ADDEB
  ,src.IMPORTO_DA_ADDEB
  ,src.NUMERO_MASSIMO_ADDEB
  ,src.PERC_ADDEB_SU_IMPONIBILE
  ,src.PERIODICITA_FATTURAZ
  ,src.UPDATE_TS
)
