UPDATE 
FAI_RECORD_C_CONDIZIONI
SET
   ALLINEAM_SCADENZA         = ?ALLINEAM_SCADENZA?
  ,AZIONE                    = ?AZIONE?
  ,CODICE_ADDEBITO           = ?CODICE_ADDEBITO?
  ,CODICE_EAN                = ?CODICE_EAN?
  ,CODICE_MINSAN             = ?CODICE_MINSAN?
  ,CODICE_PRODOTTO_OMAGGIO   = ?CODICE_PRODOTTO_OMAGGIO?
  ,DATA_FINE_VALIDITA        = ?DATA_FINE_VALIDITA?
  ,DATA_INIZIO_VALIDITA      = ?DATA_INIZIO_VALIDITA?
  ,DESCR_PRODOTTO            = ?DESCR_PRODOTTO?
  ,DESCR_PRODOTTO_OMAGGIO    = ?DESCR_PRODOTTO_OMAGGIO?
  ,DILAZIONE_PAGAM_GIORNI    = ?DILAZIONE_PAGAM_GIORNI?
  ,GIORNI_ABBU_CALC_ADD      = ?GIORNI_ABBU_CALC_ADD?
  ,PERC_ADDEBITO_AGG         = ?PERC_ADDEBITO_AGG?
  ,PERC_SC_PRZPUBDR_PRZNETUN = ?PERC_SC_PRZPUBDR_PRZNETUN?
  ,PERC_SC_PRZPUB_PRZNETUN   = ?PERC_SC_PRZPUB_PRZNETUN?
  ,PERIODICITA_FATTURAZ      = ?PERIODICITA_FATTURAZ?
  ,PREZZO_NETTO_UNITARIO     = ?PREZZO_NETTO_UNITARIO?
  ,PREZZO_VEND_LORDO_SCONTI  = ?PREZZO_VEND_LORDO_SCONTI?
  ,QUANTITA_ASSEGNATA        = ?QUANTITA_ASSEGNATA?
  ,QUANTITA_MASSIMA          = ?QUANTITA_MASSIMA?
  ,QUANTITA_MINIMA           = ?QUANTITA_MINIMA?
  ,QUANTITA_OMAGGIO          = ?QUANTITA_OMAGGIO?
  ,QUANTITA_PRODOTTO_OMAGGIO = ?QUANTITA_PRODOTTO_OMAGGIO?
  ,SCONTO_CASSA              = ?SCONTO_CASSA?
  ,SEQUENZA                  = ?SEQUENZA?
  ,SOTTOSEQUENZA             = ?SOTTOSEQUENZA?
  ,UPDATE_TS                 = SYSDATE
WHERE
OID_FORNITORE=?OID_FORNITORE? AND CODICE_CLIENTE=?CODICE_CLIENTE? AND CODICE_PRODOTTO=?CODICE_PRODOTTO?
