SELECT 
   MAGAZZINO.OID            MAGAZZINO_OID
  ,MAGAZZINO.ACRONYM        MAGAZZINO_ACRONYM
  ,MAGAZZINO.DESCR          MAGAZZINO_DESCR
  ,MAGAZZINO.COMUNE         MAGAZZINO_COMUNE
  ,MAGAZZINO.PROVINCIA      MAGAZZINO_PROVINCIA
  ,MAGAZZINO.REGIONE        MAGAZZINO_REGIONE
  ,MAGAZZINO.CAP            MAGAZZINO_CAP
  ,MAGAZZINO.INDIRIZZO      MAGAZZINO_INDIRIZZO
  ,MAGAZZINO.SUPPLIERSERVICE_CLASS_NAME
  ,TIPO_FARMACO.OID         TIPO_FARMACO_OID
  ,TIPO_FARMACO.ACRONYM     TIPO_FARMACO_ACRONYM
  ,TIPO_FARMACO.DESCR       TIPO_FARMACO_DESCR
FROM 
  FAI_MAGAZZINO                 MAGAZZINO
 ,(SELECT * FROM FAI_MAGAZZINO_TIPOFARMACO  WHERE CONTEXT ?CONTEXT?) ASSOC
 ,FAI_TIPO_FARMACO              TIPO_FARMACO
WHERE
  MAGAZZINO.OID = ASSOC.OID_MAGAZZINO (+)
  AND
  ASSOC.OID_TIPOFARMACO = TIPO_FARMACO.OID (+)
ORDER BY
  MAGAZZINO.ACRONYM  
 ,TIPO_FARMACO.ACRONYM  
