INSERT INTO FAI_DISPONIBILITA_REQ_TEMP
(
   OID
  ,OID_DISPONIBILITATEMP
  ,CODICE_MINSAN
  ,CODICE_EAN
  ,QUANTITA_RICHIESTA
)
VALUES
(
   ?OID?
  ,?OID_DISPONIBILITATEMP?
  ,?CODICE_MINSAN?
  ,?CODICE_EAN?
  ,?QUANTITA_RICHIESTA?
)