UPDATE
FAI_RECORD_V_RAGGR_COND
SET
   AZIONE                   = ?AZIONE?
  ,CODICE_ADDEBITO          = ?CODICE_ADDEBITO?
  ,DESCR_ADDEBITO           = ?DESCR_ADDEBITO?
  ,DESTINAZIONE_ADDEBITO    = ?DESTINAZIONE_ADDEBITO?
  ,IMORTO_MASSIMO_DA_ADDEB  = ?IMORTO_MASSIMO_DA_ADDEB?
  ,IMPORTO_DA_ADDEB         = ?IMPORTO_DA_ADDEB?
  ,NUMERO_MASSIMO_ADDEB     = ?NUMERO_MASSIMO_ADDEB?
  ,PERC_ADDEB_SU_IMPONIBILE = ?PERC_ADDEB_SU_IMPONIBILE?
  ,PERIODICITA_FATTURAZ     = ?PERIODICITA_FATTURAZ?
  ,UPDATE_TS                = SYSDATE
WHERE
OID_FORNITORE=?OID_FORNITORE? AND CODICE_CLIENTE=?CODICE_CLIENTE?
