UPDATE 
FAI_RECORD_A_ADDEBITO_FINANZ
SET
   AZIONE                  =?AZIONE?
  ,CODICE_ADDEBITO_FINANZ  =?CODICE_ADDEBITO_FINANZ?
  ,DESCR_ADDEBITO_FINANZ   =?DESCR_ADDEBITO_FINANZ?
  ,PERC_ADDEBITO_FINANZ    =?PERC_ADDEBITO_FINANZ? 
  ,NUM_GIORNI_ANNO_COMM    =?NUM_GIORNI_ANNO_COMM?
  ,UPDATE_TS               =SYSDATE
WHERE  
  OID_FORNITORE=?OID_FORNITORE? AND CODICE_CLIENTE=?CODICE_CLIENTE?
