SELECT FAI_FORNITORE.OID, CODICE, CODICE_FARMACLICK, SUPPLIERSERVICE_CLASS_NAME, FAI_FORNITORE_PROPERTY.OID PROP_OID,  KEY PROP_KEY, VALUE PROP_VALUE
FROM FAI_FORNITORE, FAI_FORNITORE_PROPERTY
WHERE FAI_FORNITORE.OID = FAI_FORNITORE_PROPERTY.OID_FORNITORE (+)
ORDER BY FAI_FORNITORE.OID 
