SELECT
    FAI_LISTINI_DISPONIBILITA_TEMP.OID_FORNITORE
   ,'MINSAN'					                 TIPO_CODICE	 
   ,FAI_LISTINI_DISPONIBILITA_TEMP.CODICE_MINSAN CODICE
   ,FAI_LISTINI_DISPONIBILITA_TEMP.PREZZO
FROM 
    FAI_LISTINI_DISPONIBILITA_TEMP
   ,(SELECT MIN(PREZZO) MIN_PREZZO, CODICE_MINSAN FROM FAI_LISTINI_DISPONIBILITA_TEMP WHERE OID_FORNITORE IN ?OID_LIST? GROUP BY CODICE_MINSAN) T
WHERE 
    FAI_LISTINI_DISPONIBILITA_TEMP.CODICE_MINSAN = T.CODICE_MINSAN
    AND
    FAI_LISTINI_DISPONIBILITA_TEMP.PREZZO = T.MIN_PREZZO
    AND
    FAI_LISTINI_DISPONIBILITA_TEMP.OID_FORNITORE IN ?OID_LIST?
UNION
SELECT
    FAI_LISTINI_DISPONIBILITA_TEMP.OID_FORNITORE
   ,'EAN'					                  TIPO_CODICE	 
   ,FAI_LISTINI_DISPONIBILITA_TEMP.CODICE_EAN CODICE
   ,FAI_LISTINI_DISPONIBILITA_TEMP.PREZZO
FROM 
    FAI_LISTINI_DISPONIBILITA_TEMP 
   ,(SELECT MIN(PREZZO) MIN_PREZZO, CODICE_EAN FROM FAI_LISTINI_DISPONIBILITA_TEMP WHERE OID_FORNITORE IN ?OID_LIST? GROUP BY CODICE_EAN) T
WHERE 
    FAI_LISTINI_DISPONIBILITA_TEMP.CODICE_EAN = T.CODICE_EAN
    AND
    FAI_LISTINI_DISPONIBILITA_TEMP.PREZZO = T.MIN_PREZZO
    AND
    FAI_LISTINI_DISPONIBILITA_TEMP.OID_FORNITORE IN ?OID_LIST?
