INSERT INTO FAI_APPROVVIGIONAMENTO_FARMACO
( 
   OID
  ,CODICE_MINSAN
  ,CODICE_EAN
  ,MAGAZZINO_ACRONYM
  ,QUANTITA
  ,OID_STATUS
  ,STATUS_DESCR
  ,STATUS_TECH_DESCR
  ,STATUS_UPDATED_TS
)
VALUES
(
   ? -- OID
  ,? -- CODICE_MINSAN
  ,? -- CODICE_EAN
  ,? -- MAGAZZINO_ACRONYM
  ,? -- QUANTITA
  ,? -- OID_STATUS
  ,? -- STATUS_DESCR
  ,? -- STATUS_TECH_DESCR
  ,? -- STATUS_UPDATED_TS
)
