INSERT INTO FAI_LISTINI_DISPONIBILITA_TEMP
(
    OID_FORNITORE
   ,CODICE_MINSAN
   ,CODICE_EAN
   ,PREZZO
)
(SELECT 
    v.OID_FORNITORE
   ,v.CODICE_MINSAN
   ,v.CODICE_EAN
   ,v.PREZZO
FROM 
    V_FAI_LISTINI_FORNITORI v
    inner join FAI_APPROVVIGIONAMENTO_FARMACO faf on v.codice_minsan = faf.codice_minsan
WHERE
    faf.oid_status = ?OID_STATUS?
union
SELECT 
    v.OID_FORNITORE
   ,v.CODICE_MINSAN
   ,v.CODICE_EAN
   ,v.PREZZO
FROM 
    V_FAI_LISTINI_FORNITORI v
    inner join FAI_APPROVVIGIONAMENTO_FARMACO faf on v.CODICE_EAN = faf.CODICE_EAN
WHERE
    faf.oid_status = ?OID_STATUS?
)
