INSERT INTO FAI_GROUP_EXPORT
(OID, GROUP_IDX, GROUP_NAME_EXPORT)
VALUES(oid.nextval, 1, 'GruppoProva')


INSERT INTO FAI_TABLE_EXPORT
(
 OID
,OID_GROUPEXPORT
,SQL_QUERY_IN
,SQL_QUERY_IN_FILE
,SMTWTFS_EXPORT_PATTERN
,TABLE_NAME_ORACLE
,TABLE_IDX
,TABLE_NAME_EXPORT
,SQL_DDL
,SQL_QUERY_OUT
,SQL_QUERY_OUT_FILE
)
SELECT 
 OID.NEXTVAL -- OID
,FAI_GROUP_EXPORT.OID -- OID_GROUPEXPORT
,NULL-- SQL_QUERY_IN
,NULL-- SQL_QUERY_IN_FILE
,'XXXXXXX'-- SMTWTFS_EXPORT_PATTERN
,'TABELLA_DI_PROVA'-- TABLE_NAME_ORACLE
,1 -- TABLE_IDX
,'TabellaProva' -- TABLE_NAME_EXPORT
,NULL -- SQL_DDL
,NULL -- SQL_QUERY_OUT
,NULL -- SQL_QUERY_OUT_FILE
FROM FAI_GROUP_EXPORT WHERE GROUP_NAME_EXPORT = 'GruppoProva';

INSERT INTO FAI_COLUMN_EXPORT
(
 OID
,OID_TABLEEXPORT
,COLUMN_IDX
,COLUMN_NAME_ORACLE
,COLUMN_NAME_EXPORT
,REQUIRED
,SQL_TYPE
,SQL_TYPE_LEN
,SQL_TYPE_SCALE
,DATE_FORMAT_PATTERN
,NUMB_FORMAT_PATTERN
,NUMB_FORMAT_GRPCH
,NUMB_FORMAT_DECCH
)
SELECT 
 OID.NEXTVAL -- OID
,FAI_TABLE_EXPORT.OID -- OID_TABLEEXPORT
,1 -- COLUMN_IDX
,'fornitore' -- COLUMN_NAME_ORACLE
,'fornitore' -- COLUMN_NAME_EXPORT
,'S' -- REQUIRED
,'VARCHAR2'-- SQL_TYPE
,100 -- SQL_TYPE_LEN
,NULL -- SQL_TYPE_SCALE
,NULL -- DATE_FORMAT_PATTERN
,NULL -- NUMB_FORMAT_PATTERN
,NULL -- NUMB_FORMAT_GRPCH
,NULL -- NUMB_FORMAT_DECCH
FROM FAI_TABLE_EXPORT WHERE TABLE_NAME_EXPORT = 'TabellaProva';



INSERT INTO FAI_COLUMN_EXPORT
(
 OID
,OID_TABLEEXPORT
,COLUMN_IDX
,COLUMN_NAME_ORACLE
,COLUMN_NAME_EXPORT
,REQUIRED
,SQL_TYPE
,SQL_TYPE_LEN
,SQL_TYPE_SCALE
,DATE_FORMAT_PATTERN
,NUMB_FORMAT_PATTERN
,NUMB_FORMAT_GRPCH
,NUMB_FORMAT_DECCH
)
SELECT 
 OID.NEXTVAL -- OID
,FAI_TABLE_EXPORT.OID -- OID_TABLEEXPORT
,2 -- COLUMN_IDX
,'cliente' -- COLUMN_NAME_ORACLE
,'cliente' -- COLUMN_NAME_EXPORT
,'S' -- REQUIRED
,'VARCHAR2'-- SQL_TYPE
,7 -- SQL_TYPE_LEN
,NULL -- SQL_TYPE_SCALE
,NULL -- DATE_FORMAT_PATTERN
,NULL -- NUMB_FORMAT_PATTERN
,NULL -- NUMB_FORMAT_GRPCH
,NULL -- NUMB_FORMAT_DECCH
FROM FAI_TABLE_EXPORT WHERE TABLE_NAME_EXPORT = 'TabellaProva';


INSERT INTO FAI_COLUMN_EXPORT
(
 OID
,OID_TABLEEXPORT
,COLUMN_IDX
,COLUMN_NAME_ORACLE
,COLUMN_NAME_EXPORT
,REQUIRED
,SQL_TYPE
,SQL_TYPE_LEN
,SQL_TYPE_SCALE
,DATE_FORMAT_PATTERN
,NUMB_FORMAT_PATTERN
,NUMB_FORMAT_GRPCH
,NUMB_FORMAT_DECCH
)
SELECT 
 OID.NEXTVAL -- OID
,FAI_TABLE_EXPORT.OID -- OID_TABLEEXPORT
,3 -- COLUMN_IDX
,'prodotto' -- COLUMN_NAME_ORACLE
,'prodotto' -- COLUMN_NAME_EXPORT
,'S' -- REQUIRED
,'VARCHAR2'-- SQL_TYPE
,7 -- SQL_TYPE_LEN
,NULL -- SQL_TYPE_SCALE
,NULL -- DATE_FORMAT_PATTERN
,NULL -- NUMB_FORMAT_PATTERN
,NULL -- NUMB_FORMAT_GRPCH
,NULL -- NUMB_FORMAT_DECCH
FROM FAI_TABLE_EXPORT WHERE TABLE_NAME_EXPORT = 'TabellaProva';



INSERT INTO FAI_COLUMN_EXPORT
(
 OID
,OID_TABLEEXPORT
,COLUMN_IDX
,COLUMN_NAME_ORACLE
,COLUMN_NAME_EXPORT
,REQUIRED
,SQL_TYPE
,SQL_TYPE_LEN
,SQL_TYPE_SCALE
,DATE_FORMAT_PATTERN
,NUMB_FORMAT_PATTERN
,NUMB_FORMAT_GRPCH
,NUMB_FORMAT_DECCH
)
SELECT 
 OID.NEXTVAL -- OID
,FAI_TABLE_EXPORT.OID -- OID_TABLEEXPORT
,4 -- COLUMN_IDX
,'PREZZO_AL_PUBBLICO' -- COLUMN_NAME_ORACLE
,'prezzoAlPubblico' -- COLUMN_NAME_EXPORT
,'S' -- REQUIRED
,'NUMBER'-- SQL_TYPE
,11 -- SQL_TYPE_LEN
,4 -- SQL_TYPE_SCALE
,NULL -- DATE_FORMAT_PATTERN
,NULL -- NUMB_FORMAT_PATTERN
,NULL -- NUMB_FORMAT_GRPCH
,NULL -- NUMB_FORMAT_DECCH
FROM FAI_TABLE_EXPORT WHERE TABLE_NAME_EXPORT = 'TabellaProva';



INSERT INTO FAI_COLUMN_EXPORT
(
 OID
,OID_TABLEEXPORT
,COLUMN_IDX
,COLUMN_NAME_ORACLE
,COLUMN_NAME_EXPORT
,REQUIRED
,SQL_TYPE
,SQL_TYPE_LEN
,SQL_TYPE_SCALE
,DATE_FORMAT_PATTERN
,NUMB_FORMAT_PATTERN
,NUMB_FORMAT_GRPCH
,NUMB_FORMAT_DECCH
)
SELECT 
 OID.NEXTVAL -- OID
,FAI_TABLE_EXPORT.OID -- OID_TABLEEXPORT
,5 -- COLUMN_IDX
,'DESCR_PRODOTTO' -- COLUMN_NAME_ORACLE
,'descrProdotto' -- COLUMN_NAME_EXPORT
,'S' -- REQUIRED
,'VARCHAR2'-- SQL_TYPE
,40 -- SQL_TYPE_LEN
,NULL -- SQL_TYPE_SCALE
,NULL -- DATE_FORMAT_PATTERN
,NULL -- NUMB_FORMAT_PATTERN
,NULL -- NUMB_FORMAT_GRPCH
,NULL -- NUMB_FORMAT_DECCH
FROM FAI_TABLE_EXPORT WHERE TABLE_NAME_EXPORT = 'TabellaProva';
