SELECT 
     FAI_GENERIC_TASK.OID                   GENTASK_OID           
    ,FAI_GENERIC_TASK.ACRONYM               GENTASK_ACRONYM
    ,FAI_GENERIC_TASK.DESCR                 GENTASK_DESCR
    ,FAI_GENERIC_TASK.CLASS_NAME            GENTASK_CLASS_NAME
    ,FAI_GENERIC_TASK.SCHEDULED_TIMES       GENTASK_SCHEDULED_TIMES
    ,FAI_GENERIC_TASK.SCHEDULED_SMTWTFS     GENTASK_SCHEDULED_SMTWTFS
    ,FAI_GENERIC_TASK.LAST_RUN_START_TS     GENTASK_LAST_RUN_START_TS
    ,FAI_GENERIC_TASK.LAST_RUN_END_TS       GENTASK_LAST_RUN_END_TS
    ,FAI_GENERIC_TASK.LAST_RUN_DONE         GENTASK_LAST_RUN_DONE
    ,FAI_GENERIC_TASK.LAST_RUN_DESCR        GENTASK_LAST_RUN_DESCR
    ,FAI_GENERIC_TASK.ENABLED               GENTASK_ENABLED
    , FAI_GENERIC_TASK.STATUS_DESCR         GENTASK_STATUS_DESCR
    , FAI_GENERIC_TASK.STATUS_TECH_DESCR    GENTASK_STATUS_TECH_DESCR
    ,FAI_GENERIC_TASK_PROPERTY.OID          PROP_OID
    ,FAI_GENERIC_TASK_PROPERTY.KEY          PROP_KEY
    ,FAI_GENERIC_TASK_PROPERTY.VALUE        PROP_VALUE
FROM 
     FAI_GENERIC_TASK
    ,FAI_GENERIC_TASK_PROPERTY
WHERE
    FAI_GENERIC_TASK.OID ?OID?
    AND
    FAI_GENERIC_TASK.OID = FAI_GENERIC_TASK_PROPERTY.OID_GENERICTASK (+)
ORDER BY
    FAI_GENERIC_TASK_PROPERTY.KEY
    
