SELECT APPROV.OID
     , APPROV.OID_MAGAZZINO
     , APPROV.OID_FORNITORE
     , APPROV.CODICE_MINSAN
     , APPROV.CODICE_EAN
     , APPROV.QUANTITA
     , APPROV.DISPONIBILITA_RICHIESTA_REQ
     , APPROV.DISPONIBILITA_RICHIESTA_RES
     , APPROV.DISPONIBILITA_CONFERMATA_REQ
     , APPROV.DISPONIBILITA_CONFERMATA_RES
     , APPROV.ID_ORDINE
     , APPROV.ID_RICEVUTA
     , APPROV.OID_STATUS
     , APPROV.STATUS_DESCR
     , APPROV.STATUS_TECH_DESCR
     , APPROV.STATUS_UPDATED_TS
     , APPROV.PREZZO_UNITARIO
     , APPROV.PREZZO_TOTALE
     , APPROV.ALIQUOTA_IVA
     , APPROV.ALIQUOTA_IVA_INCLUSA
     , APPROV.OID_ORDINEOUT
     , APPROV.CREATION_TS
     , APPROV.MAGAZZINO_ACRONYM
     , APPROV2RIGA.OID      APPROV2RIGA_OID
     , APPROV2RIGA.QUANTITA APPROV2RIGA_QUANTITA
     , RIGA.OID             RIGA_OID
     , RIGA.CODICE_MINSAN   RIGA_CODICE_MINSAN
     , RIGA.CODICE_EAN      RIGA_CODICE_EAN
     , RIGA.QUANTITA        RIGA_QUANTITA
     , RIGA.OID_ORDINEIN    RIGA_OID_ORDINEIN
     , ORDINE.ID_VENDITA    ID_VENDITA
     , ORDINE.QUANTITA      ORDINE_QUANTITA
FROM FAI_APPROVVIGIONAMENTO_FARMACO APPROV
         INNER JOIN FAI_APPROVVIGFARMACO_ORDINRIGA APPROV2RIGA ON APPROV2RIGA.OID_APPROVFARMACO = APPROV.OID
         INNER JOIN FAI_ORDINE_IN_RIGA_DETTAGLIO RIGA ON APPROV2RIGA.OID_ORDINEINRIGA = RIGA.OID
         INNER JOIN FAI_ORDINE_IN ORDINE ON RIGA.OID_ORDINEIN = ORDINE.OID
         ?WHERECONDITION?
?ORDERBY?
