SELECT TASK.OID               TASK_OID
     , TASK.DESCR             TASK_DESCRIPTION
     , TASK.CSV_FILE_NAME     TASK_CSV_FILE_NAME
     , TASK.MAGAZZINO_ACRONYM TASK_MAGAZZINO_ACRONYM
     , TASK.STATUS_DESCR        TASK_STATUS_DESCR
     , TASK.STATUS_TECH_DESCR TASK_STATUS_TECH_DESCR
     , CASE WHEN COLL.OID_STATUS IS NULL THEN 1  ELSE COLL.OID_STATUS END   OID_STATUS
     , COLL.STATUS_TECH_DESCR STATUS_TECH_DESCR
     , COLL.STATUS_UPDATED_TS STATUS_UPDATED_TS
     , FIS.ACRONYM            STATUS
     , FIS.DESCR              STATUS_DESCR
     , TASK.CREATION_TS       TASK_CREATION_TS

FROM FAI_UPLOAD_TASK TASK
         LEFT JOIN FAI_ORDINE_IN_COLLECTION COLL
                   ON TASK.CSV_FILE_NAME = COLL.INPUT_RESOURCE
         LEFT JOIN FAI_ITEM_STATUS FIS
                   ON COLL.OID_STATUS = FIS.OID

ORDER BY TASK.CREATION_TS

