SELECT ordine.OID
     , ID_VENDITA
     , NOME_COMPLETO_ACQUIRENTE
     , EMAIL_ACQUIRENTE
     , QUANTITA
     , OID_ORDINEINCOLLECTION
     , FULFILLED
     , PREZZO_TOTALE
     , OID_STATUS
     , STATUS_DESCR
     , STATUS_TECH_DESCR
     , STATUS_UPDATED_TS
     , ORDER_COUNT
FROM FAI_ORDINE_IN ordine,
     (SELECT COUNT(OID_ORDINEIN) ORDER_COUNT, OID_ORDINEIN OID_ORDINEIN
      FROM FAI_ORDINE_IN_RIGA_DETTAGLIO
      GROUP BY OID_ORDINEIN) T ?whereCondition? AND T.OID_ORDINEIN  = ordine.OID
ORDER BY
    CREATION_TS
