SELECT 
   ORDERS.OID
  ,ORDERS.OID_MAGAZZINO
  ,ORDERS.OID_FORNITORE
  ,ORDERS.CODICE_MINSAN
  ,ORDERS.CODICE_EAN
  ,ORDERS.QUANTITA
  ,ORDERS.DISPONIBILITA_RICHIESTA_REQ
  ,ORDERS.DISPONIBILITA_RICHIESTA_RES
  ,ORDERS.DISPONIBILITA_CONFERMATA_REQ
  ,ORDERS.DISPONIBILITA_CONFERMATA_RES
  ,ORDERS.ID_ORDINE
  ,ORDERS.ID_RICEVUTA
  ,ORDERS.OID_STATUS
  ,ORDERS.STATUS_DESCR
  ,ORDERS.STATUS_TECH_DESCR
  ,ORDERS.STATUS_UPDATED_TS
  ,ORDERS.PREZZO_UNITARIO
  ,ORDERS.PREZZO_TOTALE
  ,ORDERS.ALIQUOTA_IVA
  ,ORDERS.ALIQUOTA_IVA_INCLUSA
  ,ORDERS.OID_ORDINEOUT
  ,ORDERS.CREATION_TS
  ,ORDERS.MAGAZZINO_ACRONYM			
--  ,APPROV2RIGA.OID			        APPROV2RIGA_OID     
--  ,APPROV2RIGA.QUANTITA             APPROV2RIGA_QUANTITA
--  ,RIGA.OID							RIGA_OID          
--  ,RIGA.CODICE_MINSAN               RIGA_CODICE_MINSAN
--  ,RIGA.CODICE_EAN                  RIGA_CODICE_EAN   
--  ,RIGA.QUANTITA                    RIGA_QUANTITA     
 FROM 
   FAI_APPROVVIGIONAMENTO_FARMACO	ORDERS
  ,FAI_APPROVVIGFARMACO_ORDINRIGA	APPROV2RIGA
  ,FAI_ORDINE_IN_RIGA_DETTAGLIO		RIGA
 WHERE  
   ORDERS.OID_STATUS = ?OID_STATUS?
   AND
   APPROV2RIGA.OID_APPROVFARMACO = ORDERS.OID
   AND
   APPROV2RIGA.OID_ORDINEINRIGA  = RIGA.OID 
   AND
   ORDERS.OID_FORNITORE = ?FORNITORE_ID?
