SELECT 
     RIGA.OID
    ,RIGA.CODICE_MINSAN
    ,RIGA.CODICE_EAN
    ,RIGA.QUANTITA
    ,RIGA.MAGAZZINO_ACRONYM
FROM 
    FAI_ORDINE_IN_RIGA_DETTAGLIO    RIGA
   ,FAI_ORDINE_IN                   ORDINE
   ,FAI_ORDINE_IN_COLLECTION        COLLECTION
WHERE
    RIGA.OID_ORDINEIN = ORDINE.OID
    AND
    ORDINE.OID_ORDINEINCOLLECTION = COLLECTION.OID
    AND
    ORDINE.OID_STATUS = ?ORDINE.OID_STATUS?
    AND
    COLLECTION.OID_STATUS = ?COLLECTION.OID_STATUS?
    AND
    RIGA.IS_COUPON = 'N'
    AND
    RIGA.OID NOT IN (SELECT OID_ORDINEINRIGA FROM FAI_APPROVVIGFARMACO_ORDINRIGA)
ORDER BY
	NVL(RIGA.CODICE_MINSAN, RIGA.CODICE_EAN)
