SELECT OID, OID_FORNITORE, DATE_OF_WEEK, ATTEMPT_NUMBER FROM FAI_FORNITORE_CALENDAR
WHERE 
 DATE_OF_WEEK = ?DATE_OF_WEEK?
 AND
 (?CURRENT_TIME? between TO_CHAR(HOUR_START,'hh24:mi') AND TO_CHAR(HOUR_END,'hh24:mi'))
 ORDER BY
 OID_FORNITORE
