INSERT INTO FAI_ORDINE_IN
(
   OID
  ,OID_ORDINEINCOLLECTION
  ,ID_VENDITA
  ,ID_UTENTE
  ,NOME_COMPLETO_ACQUIRENTE
  ,NUMERO_TELEFONO_ACQUIRENTE
  ,EMAIL_ACQUIRENTE
  ,INDIRIZZO_ACQUIRENTE_1
  ,INDIRIZZO_ACQUIRENTE_2
  ,CITTA_ACQUIRENTE
  ,STATO_ACQUIRENTE
  ,CAP_ACQUIRENTE
  ,PAESE_ACQUIRENTE
  ,QUANTITA
  ,SPEDIZIONE_E_IMBALLAGGIO
  ,ASSICURAZIONE
  ,TARIFFA_PER_CONTRASSEGNO
  ,PREZZO_TOTALE
  ,METODO_DI_PAGAMENTO
  ,DATA_DI_VENDITA
  ,DATA_DEL_MODULO_DI_PAGAMENTO
  ,DATA_PAGAMENTO
  ,DATA_SPEDIZIONE
  ,DATA_FATTURA
  ,NUMERO_FATTURA
  ,FEEDBACK_LASCIATO
  ,FEEDBACK_RICEVUTO
  ,MEMO_PER_USO_PERSONALE
  ,CAMPO_PRIVATO
  ,ID_TRANSAZIONE_PAYPAL
  ,SERVIZIO_DI_SPEDIZIONE
  ,OPZIONE_CONTRASSEGNO
  ,ID_TRANSAZIONE
  ,ID_ORDINE
  ,ALIQUOTA_IVA_INCLUSA
  ,DETTAGLI_VARIAZIONE
  ,AZIENDA_ACQUIRENTE
  ,NOME_COMPLETO_FATTURAZIONE
  ,AZIENDA_FATTURAZIONE
  ,CF_FATTURAZIONE
  ,PIVA_FATTURAZIONE
  ,INDIRIZZO_FATTURAZIONE
  ,CITTA_FATTURAZIONE
  ,STATO_FATTURAZIONE
  ,CAP_FATTURAZIONE
  ,PAESE_FATTURAZIONE
  ,CODICEFE
  ,PEC
  ,NOTE
  ,OID_STATUS
  ,STATUS_DESCR
  ,STATUS_TECH_DESCR
  ,STATUS_UPDATED_TS
)
VALUES
(
   ?  -- OID
  ,?  -- OID_ORDINEINCOLLECTION
  ,?  -- ID_VENDITA
  ,?  -- ID_UTENTE
  ,?  -- NOME_COMPLETO_ACQUIRENTE
  ,?  -- NUMERO_TELEFONO_ACQUIRENTE
  ,?  -- EMAIL_ACQUIRENTE
  ,?  -- INDIRIZZO_ACQUIRENTE_1
  ,?  -- INDIRIZZO_ACQUIRENTE_2
  ,?  -- CITTA_ACQUIRENTE
  ,?  -- STATO_ACQUIRENTE
  ,?  -- CAP_ACQUIRENTE
  ,?  -- PAESE_ACQUIRENTE
  ,?  -- QUANTITA
  ,?  -- SPEDIZIONE_E_IMBALLAGGIO
  ,?  -- ASSICURAZIONE
  ,?  -- TARIFFA_PER_CONTRASSEGNO
  ,?  -- PREZZO_TOTALE
  ,?  -- METODO_DI_PAGAMENTO
  ,?  -- DATA_DI_VENDITA
  ,?  -- DATA_DEL_MODULO_DI_PAGAMENTO
  ,?  -- DATA_PAGAMENTO
  ,?  -- DATA_SPEDIZIONE
  ,?  -- DATA_FATTURA
  ,?  -- NUMERO_FATTURA
  ,?  -- FEEDBACK_LASCIATO
  ,?  -- FEEDBACK_RICEVUTO
  ,?  -- MEMO_PER_USO_PERSONALE
  ,?  -- CAMPO_PRIVATO
  ,?  -- ID_TRANSAZIONE_PAYPAL
  ,?  -- SERVIZIO_DI_SPEDIZIONE
  ,?  -- OPZIONE_CONTRASSEGNO
  ,?  -- ID_TRANSAZIONE
  ,?  -- ID_ORDINE
  ,?  -- ALIQUOTA_IVA_INCLUSA
  ,?  -- DETTAGLI_VARIAZIONE
  ,?  -- AZIENDA_ACQUIRENTE
  ,?  -- NOME_COMPLETO_FATTURAZIONE
  ,?  -- AZIENDA_FATTURAZIONE
  ,?  -- CF_FATTURAZIONE
  ,?  -- PIVA_FATTURAZIONE
  ,?  -- INDIRIZZO_FATTURAZIONE
  ,?  -- CITTA_FATTURAZIONE
  ,?  -- STATO_FATTURAZIONE
  ,?  -- CAP_FATTURAZIONE
  ,?  -- PAESE_FATTURAZIONE
  ,?  -- CODICEFE
  ,?  -- PEC
  ,?  -- NOTE
  ,?  -- OID_STATUS
  ,?  -- STATUS_DESCR
  ,?  -- STATUS_TECH_DESCR
  ,?  -- STATUS_UPDATED_TS
)
