UPDATE FAI_UPLOAD_TASK
SET
     OID_STATUS = ?OID_STATUS?
     ,STATUS_DESCR = ?STATUS_DESCR?
     ,STATUS_TECH_DESCR = ?STATUS_TECH_DESCR?
     ,STATUS_UPDATED_TS = SYSDATE
	 ,RUN_START_TS = ?RUN_START_TS?
	,RUN_END_TS = NULL
	,RUN_DONE = 'N'
	,RUN_DESCR = NULL
WHERE
    OID = ?OID?
