SELECT
    APPROV.OID
     ,APPROV.OID_MAGAZZINO
     ,APPROV.OID_FORNITORE
     ,APPROV.CODICE_MINSAN
     ,APPROV.CODICE_EAN
     ,APPROV.QUANTITA
     ,APPROV.DISPONIBILITA_RICHIESTA_REQ
     ,APPROV.DISPONIBILITA_RICHIESTA_RES
     ,APPROV.DISPONIBILITA_CONFERMATA_REQ
     ,APPROV.DISPONIBILITA_CONFERMATA_RES
     ,APPROV.ID_ORDINE
     ,APPROV.ID_RICEVUTA
     ,APPROV.OID_STATUS
     ,APPROV.STATUS_DESCR
     ,APPROV.STATUS_TECH_DESCR
     ,APPROV.STATUS_UPDATED_TS
     ,APPROV.PREZZO_UNITARIO
     ,APPROV.PREZZO_TOTALE
     ,APPROV.ALIQUOTA_IVA
     ,APPROV.ALIQUOTA_IVA_INCLUSA
     ,APPROV.OID_ORDINEOUT
     ,APPROV.CREATION_TS
     ,APPROV.MAGAZZINO_ACRONYM

     ,RIGA.OID							RIGA_OID
     ,RIGA.CODICE_MINSAN               RIGA_CODICE_MINSAN
     ,RIGA.CODICE_EAN                  RIGA_CODICE_EAN
     ,RIGA.QUANTITA                    RIGA_QUANTITA
FROM
    FAI_APPROVVIGIONAMENTO_FARMACO approv
   ,FAI_APPROVVIGFARMACO_ORDINRIGA a2r
   ,FAI_ORDINE_IN_RIGA_DETTAGLIO   riga
   ,FAI_ORDINE_IN                  ordine
   ,FAI_ITEM_STATUS                approv_status
WHERE
        approv_status.ACRONYM = 'TO PROCESS'
  AND
        approv.OID_STATUS = approv_status.OID
  AND
    approv.OID_STATUS = approv_status.OID
  AND
        approv.oid = a2r.OID_APPROVFARMACO
  AND
        a2r.OID_ORDINEINRIGA = riga.OID
  AND
        riga.OID_ORDINEIN = ordine.OID
  AND
    ordine.OID = ?oidOrdine?
ORDER BY
    approv.OID
       ,riga.oid
       , ordine.oid

