UPDATE FAI_UPLOAD_TASK
SET 
	 RUN_END_TS = SYSDATE
	,RUN_DONE = ?
	,RUN_DESCR = ?
    ,OID_STATUS = ?
    ,STATUS_DESCR = ?
    ,STATUS_TECH_DESCR = ?
    ,STATUS_UPDATED_TS = SYSDATE
WHERE
    OID = ?
