CREATE TABLE FAI_COMIFAR_WS
(
	CREATION_TS          DATE DEFAULT  SYSDATE  CONSTRAINT NN_COMIFARWS_CREATS NOT NULL ,
	RESULT_FILE           CLOB NULL ,
	SERVICE_NAME         VARCHAR2(20) CONSTRAINT NN_COMIFARWS_SNAME NOT NULL ,
	SERVICE_PARAMS       VARCHAR2(200) NULL ,
	OID                  INTEGER CONSTRAINT NN_COMIFARWS_OID NOT NULL ,
	RESULT_SUCCESS       CHAR(1) NULL  CONSTRAINT  CK_OMIFARWS_RESS CHECK (RESULT_SUCCESS IN ('S', 'N')),
	RESULT_DESCR         VARCHAR2(100) NULL 
);

CREATE UNIQUE INDEX UX_COMIFARWS_OID ON FAI_COMIFAR_WS
(OID   ASC)
	TABLESPACE FAI_IDX;

ALTER TABLE FAI_COMIFAR_WS
	ADD CONSTRAINT  PK_COMIFARWS PRIMARY KEY (OID);
	
	
	

CREATE TABLE FAI_COMIFAR_LISTINO
(
	OID                  INTEGER CONSTRAINT NN_COMIFAR_OID NOT NULL ,
	STATO                CHAR(1) NULL ,
	CODICE_CLIENTE       VARCHAR2(7) NULL ,
	CODICE_MINSAN        VARCHAR2(9) NULL ,
	NOTA_PRODOTTO        VARCHAR2(40) NULL ,
	ALIQUOTA_IVA         NUMBER(3,1) NULL ,
	SCONTO	             NUMBER(4,2) NULL ,
	VALID_FROM_TS        DATE CONSTRAINT NN_COMIFAR_CREAVDAL NOT NULL ,
	VALID_TO_TS          DATE CONSTRAINT NN_COMIFAR_CREAVDA NOT NULL ,
	CREATION_TS DATE DEFAULT SYSDATE,
	UPDATE_TS            DATE CONSTRAINT NN_COMIFAR_UPDTS NOT NULL 
);

CREATE UNIQUE INDEX UX_COMIFARL_OID ON FAI_COMIFAR_LISTINO
(OID   ASC)
	TABLESPACE FAI_IDX;

ALTER TABLE FAI_COMIFAR_LISTINO
	ADD CONSTRAINT  PK_COMIFARL PRIMARY KEY (OID);

CREATE INDEX IX_COMIFARL_CODCLI ON FAI_COMIFAR_LISTINO
(CODICE_CLIENTE   ASC)
	TABLESPACE FAI_IDX;



CREATE TABLE FAI_COMIFAR_LISTINO_PRICE
(
	OID                  INTEGER CONSTRAINT NN_COMIFAR_PRICE_OID NOT NULL ,
	OID_COMIFAR_LISTINO  INTEGER CONSTRAINT NN_RECL_COMIFAR_PRICE NOT NULL ,
	QUANTITA       		 INTEGER NULL,
	PREZZO_NETTO         NUMBER(13,6) NULL,
	CREATION_TS DATE DEFAULT SYSDATE,
	UPDATE_TS            DATE CONSTRAINT NN_COMIFAR_PRICE_UPDTS NOT NULL 
);

CREATE UNIQUE INDEX UX_COMIFAR_LISTINO_PRICE_OID ON FAI_COMIFAR_LISTINO_PRICE
(OID   ASC)
	TABLESPACE FAI_IDX;

ALTER TABLE FAI_COMIFAR_LISTINO_PRICE
	ADD CONSTRAINT  PK_COMIFAR_LISTINO_PRICE PRIMARY KEY (OID);
	
	
	
	
ALTER TABLE FAI_COMIFAR_LISTINO_PRICE
	ADD (CONSTRAINT FK_RECL_COMIFAR_LISTINO FOREIGN KEY (OID_COMIFAR_LISTINO) REFERENCES FAI_COMIFAR_LISTINO (OID));
