
CREATE SEQUENCE OID;

CREATE TABLE FAI_FARMADATI_DDL
(
	OID                  INTEGER CONSTRAINT NN_FARMDTDDL_OID NOT NULL ,
	TABLE_NAME           VARCHAR2(30) CONSTRAINT NN_FARMDTDDL_TNAME NOT NULL ,
	SQL_CREATE           CLOB CONSTRAINT NN_FARMDTDDL_SQLC NOT NULL ,
	CREATION_TS          DATE DEFAULT  SYSDATE  CONSTRAINT NN_FARMDTDDL_CREATS NOT NULL ,
	NO_LONGER_EXISTS_TS  DATE NULL ,
	ALL_DATA_LOADED_TS   DATE NULL 
);

CREATE UNIQUE INDEX UX_FARMDTDDL_OID ON FAI_FARMADATI_DDL
(OID   ASC)
	TABLESPACE FAI_IDX;

ALTER TABLE FAI_FARMADATI_DDL
	ADD CONSTRAINT  PK_FARMDTDDL PRIMARY KEY (OID);

CREATE TABLE FAI_FARMADATI_TABLE_TO_IGNORE
(
	TABLE_NAME           VARCHAR2(30) NULL 
);

CREATE TABLE FAI_FARMADATI_WS
(
	CREATION_TS          DATE DEFAULT  SYSDATE  CONSTRAINT NN_FARMDTWS_CREATS NOT NULL ,
	RESULT_XML           CLOB NULL ,
	SERVICE_NAME         VARCHAR2(20) CONSTRAINT NN_FARMDTWS_SNAME NOT NULL ,
	SERVICE_PARAMS       VARCHAR2(200) NULL ,
	OID                  INTEGER CONSTRAINT NN_FARMDTWS_OID NOT NULL ,
	RESULT_SUCCESS       CHAR(1) NULL  CONSTRAINT  CK_FARMDTWS_RESS CHECK (RESULT_SUCCESS IN ('S', 'N')),
	RESULT_DESCR         VARCHAR2(100) NULL 
);

CREATE UNIQUE INDEX UX_FARMDTWS_OID ON FAI_FARMADATI_WS
(OID   ASC)
	TABLESPACE FAI_IDX;

ALTER TABLE FAI_FARMADATI_WS
	ADD CONSTRAINT  PK_FARMDTWS PRIMARY KEY (OID);

CREATE TABLE FAI_FARMADATI_WS_CONFIG
(
	WS_URL               VARCHAR2(500) CONSTRAINT NN_FDCFG_WSURL NOT NULL ,
	WS_LOGIN             VARCHAR2(200) CONSTRAINT NN_FDCFG_WSLOGIN NULL ,
	WS_PASSWORD          VARCHAR2(200) CONSTRAINT NN_FDCFG_WSPASS NULL ,
	WS_QUERY_INTERVAL    INTEGER CONSTRAINT NN_FDCFG_QUERYINT NOT NULL ,
	WS_QUERY_TIME        DATE CONSTRAINT NN_FDCFG_QUERYTIME NOT NULL ,
	WS_PASSWORD_ENCR     CHAR(1) DEFAULT  'N'  CONSTRAINT NN_FDCFG_WSPASSENCR NOT NULL  CONSTRAINT  CK_FDCFG_WSPASSENCR CHECK (WS_PASSWORD_ENCR IN ('S', 'N')),
	DEBUG_MODE           VARCHAR2(20) CONSTRAINT NN_FDCFG_DEBUGMODE NOT NULL  CONSTRAINT  CK_FDCFG_DEBUGMODE CHECK (DEBUG_MODE IN ('S', 'N')),
	RESUME_PREV_SESSION_MODE CHAR(1) CONSTRAINT NN_FDCFG_RSMEPRVSMODE NOT NULL  CONSTRAINT  CK_FDCFG_RSMEPRVSMODE CHECK (RESUME_PREV_SESSION_MODE IN ('S', 'N'))
);

CREATE TABLE FAI_FARMADATI_WS_STATUS
(
	LAST_RUN_START_TS    DATE NULL ,
	LAST_RUN_END_TS      DATE NULL ,
	LAST_RUN_DONE        CHAR(1) CONSTRAINT NN_STATUS_LRUNDONE NOT NULL  CONSTRAINT  CK_STATUS_LRUNDONE CHECK (LAST_RUN_DONE IN ('S', 'N')),
	LAST_RUN_DESCR       VARCHAR2(2000) NULL 
);

CREATE TABLE SD_SCHEMA_VERSION
(
	VERSION              VARCHAR2(64) CONSTRAINT NN_SDSCHVER_VER NOT NULL ,
	LAST_MODIFY          DATE CONSTRAINT NN_SDSCHVER_LMOD NOT NULL 
);
