MERGE INTO FAI_FARMACLICK_FORNITORE
USING (
	SELECT ?CODICE? CODICE FROM DUAL

) IDENTIFIER
ON 
    (FAI_FARMACLICK_FORNITORE.CODICE = IDENTIFIER.CODICE)
WHEN 
    MATCHED THEN
	UPDATE SET
        CODICE_SITO_LOGISTICO    = ?CODICE_SITO_LOGISTICO? 
       ,DESCRIZIONE_BREVE        = ?DESCRIZIONE_BREVE? 
       ,LAST_CSV                 = NULL
       ,LAST_CSV_ZIPPED          = ?LAST_CSV_ZIPPED?
       ,LAST_CSV_FILENAME        = NULL 
       ,LAST_CSV_DOWNLOAD_URL    = ?LAST_CSV_DOWNLOAD_URL? 
       ,LAST_CSV_DOWNLOAD_AT_TS  = NULL 
       ,LAST_CSV_CONFIRM_URL     = ?LAST_CSV_CONFIRM_URL?
       ,LAST_CSV_CONFIRMED_AT_TS = NULL 
       ,NO_LONGER_EXISTS_TS      = NULL 
       ,ALL_DATA_STORED_TS       = NULL 
WHEN
    NOT MATCHED THEN
	INSERT (
	    OID
	   ,CODICE                   
       ,CODICE_SITO_LOGISTICO    
       ,DESCRIZIONE_BREVE        
       ,LAST_CSV                 
       ,LAST_CSV_ZIPPED          
       ,LAST_CSV_FILENAME        
       ,LAST_CSV_DOWNLOAD_URL    
       ,LAST_CSV_DOWNLOAD_AT_TS  
       ,LAST_CSV_CONFIRM_URL     
       ,LAST_CSV_CONFIRMED_AT_TS 
       ,NO_LONGER_EXISTS_TS      
       ,ALL_DATA_STORED_TS       
    )
	VALUES (
	    OID.NEXTVAL
	   ,?CODICE?                   
       ,?CODICE_SITO_LOGISTICO?    
       ,?DESCRIZIONE_BREVE?   
       ,NULL       
       ,?LAST_CSV_ZIPPED?
       ,NULL        
       ,?LAST_CSV_DOWNLOAD_URL?    
       ,NULL  
       ,?LAST_CSV_CONFIRM_URL?     
       ,NULL 
       ,NULL      
       ,NULL       
    )
