MERGE INTO FAI_RECORD_C_CONDIZIONI tgt
USING
(
SELECT
   ?OID_FORNITORE?              OID_FORNITORE
  ,?ALLINEAM_SCADENZA?          ALLINEAM_SCADENZA
  ,?AZIONE?                     AZIONE
  ,?CODICE_ADDEBITO?            CODICE_ADDEBITO
  ,?CODICE_CLIENTE?             CODICE_CLIENTE
  ,?CODICE_EAN?                 CODICE_EAN
  ,?CODICE_MINSAN?              CODICE_MINSAN
  ,?CODICE_PRODOTTO?            CODICE_PRODOTTO
  ,?CODICE_PRODOTTO_OMAGGIO?    CODICE_PRODOTTO_OMAGGIO
  ,SYSDATE                      CREATION_TS
  ,?DATA_FINE_VALIDITA?         DATA_FINE_VALIDITA
  ,?DATA_INIZIO_VALIDITA?       DATA_INIZIO_VALIDITA
  ,?DESCR_PRODOTTO?             DESCR_PRODOTTO
  ,?DESCR_PRODOTTO_OMAGGIO?     DESCR_PRODOTTO_OMAGGIO
  ,?DILAZIONE_PAGAM_GIORNI?     DILAZIONE_PAGAM_GIORNI
  ,?GIORNI_ABBU_CALC_ADD?       GIORNI_ABBU_CALC_ADD
  ,?PERC_ADDEBITO_AGG?          PERC_ADDEBITO_AGG
  ,?PERC_SC_PRZPUBDR_PRZNETUN?  PERC_SC_PRZPUBDR_PRZNETUN
  ,?PERC_SC_PRZPUB_PRZNETUN?    PERC_SC_PRZPUB_PRZNETUN
  ,?PERIODICITA_FATTURAZ?       PERIODICITA_FATTURAZ
  ,?PREZZO_NETTO_UNITARIO?      PREZZO_NETTO_UNITARIO
  ,?PREZZO_VEND_LORDO_SCONTI?   PREZZO_VEND_LORDO_SCONTI
  ,?QUANTITA_ASSEGNATA?         QUANTITA_ASSEGNATA
  ,?QUANTITA_MASSIMA?           QUANTITA_MASSIMA
  ,?QUANTITA_MINIMA?            QUANTITA_MINIMA
  ,?QUANTITA_OMAGGIO?           QUANTITA_OMAGGIO
  ,?QUANTITA_PRODOTTO_OMAGGIO?  QUANTITA_PRODOTTO_OMAGGIO
  ,?SCONTO_CASSA?               SCONTO_CASSA
  ,?SEQUENZA?                   SEQUENZA
  ,?SOTTOSEQUENZA?              SOTTOSEQUENZA
  ,SYSDATE                      UPDATE_TS
FROM DUAL
) src
ON (tgt.OID_FORNITORE=src.OID_FORNITORE AND tgt.CODICE_CLIENTE=src.CODICE_CLIENTE AND tgt.CODICE_PRODOTTO=src.CODICE_PRODOTTO)
WHEN MATCHED
THEN UPDATE SET
   tgt.ALLINEAM_SCADENZA         = src.ALLINEAM_SCADENZA
  ,tgt.AZIONE                    = src.AZIONE
  ,tgt.CODICE_ADDEBITO           = src.CODICE_ADDEBITO
  ,tgt.CODICE_EAN                = src.CODICE_EAN
  ,tgt.CODICE_MINSAN             = src.CODICE_MINSAN
  ,tgt.CODICE_PRODOTTO_OMAGGIO   = src.CODICE_PRODOTTO_OMAGGIO
  ,tgt.DATA_FINE_VALIDITA        = src.DATA_FINE_VALIDITA
  ,tgt.DATA_INIZIO_VALIDITA      = src.DATA_INIZIO_VALIDITA
  ,tgt.DESCR_PRODOTTO            = src.DESCR_PRODOTTO
  ,tgt.DESCR_PRODOTTO_OMAGGIO    = src.DESCR_PRODOTTO_OMAGGIO
  ,tgt.DILAZIONE_PAGAM_GIORNI    = src.DILAZIONE_PAGAM_GIORNI
  ,tgt.GIORNI_ABBU_CALC_ADD      = src.GIORNI_ABBU_CALC_ADD
  ,tgt.PERC_ADDEBITO_AGG         = src.PERC_ADDEBITO_AGG
  ,tgt.PERC_SC_PRZPUBDR_PRZNETUN = src.PERC_SC_PRZPUBDR_PRZNETUN
  ,tgt.PERC_SC_PRZPUB_PRZNETUN   = src.PERC_SC_PRZPUB_PRZNETUN
  ,tgt.PERIODICITA_FATTURAZ      = src.PERIODICITA_FATTURAZ
  ,tgt.PREZZO_NETTO_UNITARIO     = src.PREZZO_NETTO_UNITARIO
  ,tgt.PREZZO_VEND_LORDO_SCONTI  = src.PREZZO_VEND_LORDO_SCONTI
  ,tgt.QUANTITA_ASSEGNATA        = src.QUANTITA_ASSEGNATA
  ,tgt.QUANTITA_MASSIMA          = src.QUANTITA_MASSIMA
  ,tgt.QUANTITA_MINIMA           = src.QUANTITA_MINIMA
  ,tgt.QUANTITA_OMAGGIO          = src.QUANTITA_OMAGGIO
  ,tgt.QUANTITA_PRODOTTO_OMAGGIO = src.QUANTITA_PRODOTTO_OMAGGIO
  ,tgt.SCONTO_CASSA              = src.SCONTO_CASSA
  ,tgt.SEQUENZA                  = src.SEQUENZA
  ,tgt.SOTTOSEQUENZA             = src.SOTTOSEQUENZA
  ,tgt.UPDATE_TS                 = src.UPDATE_TS
WHEN NOT MATCHED
THEN INSERT
(
   OID
  ,OID_FORNITORE
  ,ALLINEAM_SCADENZA
  ,AZIONE
  ,CODICE_ADDEBITO
  ,CODICE_CLIENTE
  ,CODICE_EAN
  ,CODICE_MINSAN
  ,CODICE_PRODOTTO
  ,CODICE_PRODOTTO_OMAGGIO
  ,CREATION_TS
  ,DATA_FINE_VALIDITA
  ,DATA_INIZIO_VALIDITA
  ,DESCR_PRODOTTO
  ,DESCR_PRODOTTO_OMAGGIO
  ,DILAZIONE_PAGAM_GIORNI
  ,GIORNI_ABBU_CALC_ADD
  ,PERC_ADDEBITO_AGG
  ,PERC_SC_PRZPUBDR_PRZNETUN
  ,PERC_SC_PRZPUB_PRZNETUN
  ,PERIODICITA_FATTURAZ
  ,PREZZO_NETTO_UNITARIO
  ,PREZZO_VEND_LORDO_SCONTI
  ,QUANTITA_ASSEGNATA
  ,QUANTITA_MASSIMA
  ,QUANTITA_MINIMA
  ,QUANTITA_OMAGGIO
  ,QUANTITA_PRODOTTO_OMAGGIO
  ,SCONTO_CASSA
  ,SEQUENZA
  ,SOTTOSEQUENZA
  ,UPDATE_TS
)
VALUES
(
   OID.NEXTVAL
  ,src.OID_FORNITORE
  ,src.ALLINEAM_SCADENZA
  ,src.AZIONE
  ,src.CODICE_ADDEBITO
  ,src.CODICE_CLIENTE
  ,src.CODICE_EAN
  ,src.CODICE_MINSAN
  ,src.CODICE_PRODOTTO
  ,src.CODICE_PRODOTTO_OMAGGIO
  ,src.CREATION_TS
  ,src.DATA_FINE_VALIDITA
  ,src.DATA_INIZIO_VALIDITA
  ,src.DESCR_PRODOTTO
  ,src.DESCR_PRODOTTO_OMAGGIO
  ,src.DILAZIONE_PAGAM_GIORNI
  ,src.GIORNI_ABBU_CALC_ADD
  ,src.PERC_ADDEBITO_AGG
  ,src.PERC_SC_PRZPUBDR_PRZNETUN
  ,src.PERC_SC_PRZPUB_PRZNETUN
  ,src.PERIODICITA_FATTURAZ
  ,src.PREZZO_NETTO_UNITARIO
  ,src.PREZZO_VEND_LORDO_SCONTI
  ,src.QUANTITA_ASSEGNATA
  ,src.QUANTITA_MASSIMA
  ,src.QUANTITA_MINIMA
  ,src.QUANTITA_OMAGGIO
  ,src.QUANTITA_PRODOTTO_OMAGGIO
  ,src.SCONTO_CASSA
  ,src.SEQUENZA
  ,src.SOTTOSEQUENZA
  ,src.UPDATE_TS
)
