MERGE INTO FAI_RECORD_R_RAGGR_COND tgt
USING
(
SELECT
   ?OID_FORNITORE?           OID_FORNITORE
  ,?AZIONE?                  AZIONE
  ,?CODICE_CLIENTE?          CODICE_CLIENTE
  ,?CODICE_REGGRUPP_CONDIZ?  CODICE_REGGRUPP_CONDIZ
  ,SYSDATE                   CREATION_TS
  ,?DESCR_REGGRUPP_CONDIZ?   DESCR_REGGRUPP_CONDIZ
  ,?RIGA?                    RIGA
  ,SYSDATE                   UPDATE_TS
FROM DUAL
) src
ON (tgt.OID_FORNITORE=src.OID_FORNITORE AND tgt.CODICE_CLIENTE=src.CODICE_CLIENTE)
WHEN MATCHED
THEN UPDATE SET
   tgt.AZIONE                 = src.AZIONE
  ,tgt.CODICE_REGGRUPP_CONDIZ = src.CODICE_REGGRUPP_CONDIZ
  ,tgt.DESCR_REGGRUPP_CONDIZ  = src.DESCR_REGGRUPP_CONDIZ
  ,tgt.RIGA                   = src.RIGA
  ,tgt.UPDATE_TS              = src.UPDATE_TS
WHEN NOT MATCHED
THEN INSERT
(
   OID
  ,OID_FORNITORE
  ,AZIONE
  ,CODICE_CLIENTE
  ,CODICE_REGGRUPP_CONDIZ
  ,CREATION_TS
  ,DESCR_REGGRUPP_CONDIZ
  ,RIGA
  ,UPDATE_TS
)
VALUES
(
   OID.NEXTVAL
  ,src.OID_FORNITORE
  ,src.AZIONE
  ,src.CODICE_CLIENTE
  ,src.CODICE_REGGRUPP_CONDIZ
  ,src.CREATION_TS
  ,src.DESCR_REGGRUPP_CONDIZ
  ,src.RIGA
  ,src.UPDATE_TS
)
