MERGE INTO FAI_RECORD_A_ADDEBITO_FINANZ tgt
USING
(
SELECT
   ?OID_FORNITORE?           OID_FORNITORE
  ,?AZIONE?                  AZIONE
  ,?CODICE_CLIENTE?          CODICE_CLIENTE
  ,?CODICE_ADDEBITO_FINANZ?  CODICE_ADDEBITO_FINANZ
  ,?DESCR_ADDEBITO_FINANZ?   DESCR_ADDEBITO_FINANZ
  ,?PERC_ADDEBITO_FINANZ?    PERC_ADDEBITO_FINANZ
  ,?NUM_GIORNI_ANNO_COMM?    NUM_GIORNI_ANNO_COMM
  ,SYSDATE                   CREATION_TS
  ,SYSDATE                   UPDATE_TS
FROM DUAL
) src
ON (tgt.OID_FORNITORE=src.OID_FORNITORE AND tgt.CODICE_CLIENTE=src.CODICE_CLIENTE)
WHEN MATCHED
THEN UPDATE SET
   tgt.AZIONE                  =src.AZIONE
  ,tgt.CODICE_ADDEBITO_FINANZ  =src.CODICE_ADDEBITO_FINANZ
  ,tgt.DESCR_ADDEBITO_FINANZ   =src.DESCR_ADDEBITO_FINANZ
  ,tgt.PERC_ADDEBITO_FINANZ    =src.PERC_ADDEBITO_FINANZ
  ,tgt.NUM_GIORNI_ANNO_COMM    =src.NUM_GIORNI_ANNO_COMM
  ,tgt.UPDATE_TS               =src.UPDATE_TS
WHEN NOT MATCHED
THEN INSERT 
 (
   OID
  ,OID_FORNITORE
  ,AZIONE
  ,CODICE_CLIENTE
  ,CODICE_ADDEBITO_FINANZ
  ,DESCR_ADDEBITO_FINANZ
  ,PERC_ADDEBITO_FINANZ
  ,NUM_GIORNI_ANNO_COMM
  ,CREATION_TS
  ,UPDATE_TS
)
VALUES (
   OID.NEXTVAL
  ,src.OID_FORNITORE
  ,src.AZIONE
  ,src.CODICE_CLIENTE
  ,src.CODICE_ADDEBITO_FINANZ
  ,src.DESCR_ADDEBITO_FINANZ
  ,src.PERC_ADDEBITO_FINANZ
  ,src.NUM_GIORNI_ANNO_COMM
  ,src.CREATION_TS
  ,src.UPDATE_TS
)
