MERGE INTO FAI_GENERIC_TASK_PROPERTY tgt
USING
(
SELECT
   FAI_GENERIC_TASK.OID  OID_GENERICTASK
  ,?  KEY
  ,?  VALUE
FROM FAI_GENERIC_TASK WHERE ACRONYM = ?
) src
ON (tgt.KEY=src.KEY)
WHEN MATCHED
THEN UPDATE SET
   tgt.OID_GENERICTASK = src.OID_GENERICTASK
  ,tgt.VALUE           = src.VALUE
WHEN NOT MATCHED
THEN INSERT
(
   OID
  ,OID_GENERICTASK
  ,KEY
  ,VALUE
)
VALUES
(
   OID.NEXTVAL
  ,src.OID_GENERICTASK
  ,src.KEY
  ,src.VALUE
)
