package fai.imp.farmadati.csv;

import java.util.ArrayList;
import java.util.List;

import fai.common.csv.CsvOutputStream;
import fai.common.util.NumberFormatFactory;

public class FarmadatiCsvOutputStreamFactory {
  
  private static List<String> headersWithDefaults = null;
  
  private static synchronized void initHeadersAndDefaults() throws Exception {
    if (headersWithDefaults != null) return;
    headersWithDefaults = new ArrayList<String>();
    headersWithDefaults.add("Transaction Type;UPDATE");
    headersWithDefaults.add("Batch ID;");
    headersWithDefaults.add("Batch Number;1");
    headersWithDefaults.add("Item Number;367058");
    headersWithDefaults.add("OUTSIDE_PROCESS_SERVICE_FLAG;N");
    headersWithDefaults.add("Organization Code;FAI_ITEM");
    headersWithDefaults.add("Description;TISANA KELEMATA*ERBE OS 80G");
    headersWithDefaults.add("Template Name;");
    headersWithDefaults.add("Source System Code;PIMDH");
    headersWithDefaults.add("Source System Reference;");
    headersWithDefaults.add("Source System Reference Description;");
    headersWithDefaults.add("Item Class Name;Root Item Class");
    headersWithDefaults.add("Primary Unit of Measure;Unit");
    headersWithDefaults.add("Lifecycle Phase;Production");
    headersWithDefaults.add("Item Status;Active");
    headersWithDefaults.add("New Item Class Name;");
    headersWithDefaults.add("Asset Tracked;");
    headersWithDefaults.add("Allow Maintenance Asset;N");
    headersWithDefaults.add("Enable Genealogy Flag;Y");
    headersWithDefaults.add("Asset Class;");
    headersWithDefaults.add("Asset Item Type;");
    headersWithDefaults.add("Activity Type;");
    headersWithDefaults.add("Activity Cause;");
    headersWithDefaults.add("Activity Notification Required;");
    headersWithDefaults.add("Shutdown Type;");
    headersWithDefaults.add("Activity Source;");
    headersWithDefaults.add("Costing Enabled;N");
    headersWithDefaults.add("Standard Lot Size;");
    headersWithDefaults.add("Inventory Asset Value;N");
    headersWithDefaults.add("Include in Rollup;");
    headersWithDefaults.add("Order Cost;");
    headersWithDefaults.add("Minimum Days of Supply;");
    headersWithDefaults.add("Fixed Quantity;");
    headersWithDefaults.add("Minimum Order;");
    headersWithDefaults.add("Automatically Expire ASN;");
    headersWithDefaults.add("Carrying Cost Percentage;");
    headersWithDefaults.add("Consigned;");
    headersWithDefaults.add("Fixed Days Supply;");
    headersWithDefaults.add("Fixed Lot Size Multiplier;");
    headersWithDefaults.add("Fixed Order Quantity;");
    headersWithDefaults.add("Window Days;");
    headersWithDefaults.add("Inventory Planning Method;");
    headersWithDefaults.add("Safety Stock Planning Method;");
    headersWithDefaults.add("Demand Period;");
    headersWithDefaults.add("Days Of Cover;");
    headersWithDefaults.add("Minimum Min-Max Quantity;");
    headersWithDefaults.add("Maximum Min-Max Quantity;");
    headersWithDefaults.add("Minimum Order Quantity;");
    headersWithDefaults.add("Maximum Order Quantity;");
    headersWithDefaults.add("Planner;");
    headersWithDefaults.add("Make or Buy;");
    headersWithDefaults.add("Source Subinventory;");
    headersWithDefaults.add("Replenishment Source Type;");
    headersWithDefaults.add("Release Authorization Required;");
    headersWithDefaults.add("Subcontracting Component;");
    headersWithDefaults.add("Forecast Type;");
    headersWithDefaults.add("Maximum Order;");
    headersWithDefaults.add("Maximum Days of Supply;");
    headersWithDefaults.add("Source Organization;");
    headersWithDefaults.add("Subinventory Restrictions;");
    headersWithDefaults.add("Restrict Locators;");
    headersWithDefaults.add("Child Lot Enabled;");
    headersWithDefaults.add("Child Lot Prefix;");
    headersWithDefaults.add("Child Lot Starting Number;");
    headersWithDefaults.add("Child Lot Format Validation;");
    headersWithDefaults.add("Copy Lot Attributes;");
    headersWithDefaults.add("Expiration Action;");
    headersWithDefaults.add("Expiration Action Interval;");
    headersWithDefaults.add("Stocked;");
    headersWithDefaults.add("Starting Lot Number;");
    headersWithDefaults.add("Lot Expiration Control;");
    headersWithDefaults.add("Shelf Life Days;");
    headersWithDefaults.add("Serial Number Control;");
    headersWithDefaults.add("Serial Status Enabled;");
    headersWithDefaults.add("Revision Control;");
    headersWithDefaults.add("Retest Interval;");
    headersWithDefaults.add("Starting Lot Prefix;");
    headersWithDefaults.add("Starting Serial Prefix;");
    headersWithDefaults.add("Bulk Picked;");
    headersWithDefaults.add("Check Material Shortage;");
    headersWithDefaults.add("Cycle Count Enabled;");
    headersWithDefaults.add("Default Grade;");
    headersWithDefaults.add("Grade Controlled;");
    headersWithDefaults.add("Hold Days;");
    headersWithDefaults.add("Lot Divisible;");
    headersWithDefaults.add("Maturity Days;");
    headersWithDefaults.add("Default Lot Status;");
    headersWithDefaults.add("Default Serial Status;");
    headersWithDefaults.add("Lot Split Enabled;");
    headersWithDefaults.add("Lot Merge Enabled;");
    headersWithDefaults.add("Inventory Item;Y");
    headersWithDefaults.add("Stock Locator Control;");
    headersWithDefaults.add("Lot Control;");
    headersWithDefaults.add("Lot Status Enabled;");
    headersWithDefaults.add("Lot Substitution Enabled;");
    headersWithDefaults.add("Lot Translate Enabled;");
    headersWithDefaults.add("Transaction Enabled;Y");
    headersWithDefaults.add("Positive Measurement Error;");
    headersWithDefaults.add("Negative Measurement Error;");
    headersWithDefaults.add("Child Lot Generation;");
    headersWithDefaults.add("Reservable;");
    headersWithDefaults.add("Starting Serial Number;");
    headersWithDefaults.add("Invoicing Rule;");
    headersWithDefaults.add("Output Tax Classification Code;");
    headersWithDefaults.add("Sales Account;");
    headersWithDefaults.add("Payment Terms;");
    headersWithDefaults.add("Invoice Enabled;Y");
    headersWithDefaults.add("Invoiced;Y");
    headersWithDefaults.add("Accounting Rule;");
    headersWithDefaults.add("Autocreated Configuration;");
    headersWithDefaults.add("Assemble to Order;");
    headersWithDefaults.add("Pick Components;");
    headersWithDefaults.add("Base Model;");
    headersWithDefaults.add("Effectivity Control;");
    headersWithDefaults.add("Create Configured Item;");
    headersWithDefaults.add("Match Configuration;");
    headersWithDefaults.add("Configurator Model Type;");
    headersWithDefaults.add("Structure Item Type;");
    headersWithDefaults.add("Cumulative Manufacturing Lead Time;");
    headersWithDefaults.add("Preprocessing Days;");
    headersWithDefaults.add("Cumulative Total Lead Time;");
    headersWithDefaults.add("Fixed Lead Time;");
    headersWithDefaults.add("Variable Lead Time;");
    headersWithDefaults.add("Processing Days;");
    headersWithDefaults.add("Lead Time Lot Size;");
    headersWithDefaults.add("Postprocessing Days;");
    headersWithDefaults.add("Forecast Control;");
    headersWithDefaults.add("Critical Component;");
    headersWithDefaults.add("Acceptable Early Days;");
    headersWithDefaults.add("Create Supply;");
    headersWithDefaults.add("Target Inventory Days of Supply;");
    headersWithDefaults.add("Target Inventory Window;");
    headersWithDefaults.add("Maximum Inventory Days of Supply;");
    headersWithDefaults.add("Maximum Inventory Window;");
    headersWithDefaults.add("Demand Time Fence;");
    headersWithDefaults.add("Demand Time Days;");
    headersWithDefaults.add("Distribution Planned;");
    headersWithDefaults.add("End Assembly Pegging;");
    headersWithDefaults.add("Exclude from Budget;");
    headersWithDefaults.add("Calculate ATP;");
    headersWithDefaults.add("Planning Method;7");
    headersWithDefaults.add("Planned Inventory Point;");
    headersWithDefaults.add("Planning Time Fence Code;");
    headersWithDefaults.add("Planning Time Fence Days;");
    headersWithDefaults.add("Preposition Point;");
    headersWithDefaults.add("Release Time Fence Code;");
    headersWithDefaults.add("Release Time Fence Days;");
    headersWithDefaults.add("Repair Lead Time;");
    headersWithDefaults.add("Repair Yield;");
    headersWithDefaults.add("Repair Program;");
    headersWithDefaults.add("Round Order Quantities;");
    headersWithDefaults.add("Shrinkage Rate;");
    headersWithDefaults.add("Substitution Window Code;");
    headersWithDefaults.add("Substitution Window Days;");
    headersWithDefaults.add("Pack Type;CASE");
    headersWithDefaults.add("Conversions;");
    headersWithDefaults.add("Positive Deviation Factor;");
    headersWithDefaults.add("Negative Deviation Factor;");
    headersWithDefaults.add("User Item Type;FG");
    headersWithDefaults.add("Long Description;TISANA KELEMATA*ERBE OS 80G");
    headersWithDefaults.add("Formatted Description;TISANA KELEMATA*ERBE OS 80G");
    headersWithDefaults.add("Pricing Unit of Measure;");
    headersWithDefaults.add("Defaulting Control;");
    headersWithDefaults.add("Secondary Unit of Measure;");
    headersWithDefaults.add("Tracking Unit of Measure;");
    headersWithDefaults.add("Engineered Item Flag;");
    headersWithDefaults.add("ATP Components;");
    headersWithDefaults.add("Check ATP;");
    headersWithDefaults.add("Over Shipment Tolerance;");
    headersWithDefaults.add("Under Shipment Tolerance;");
    headersWithDefaults.add("Over Return Tolerance;");
    headersWithDefaults.add("Under Return Tolerance;");
    headersWithDefaults.add("Downloadable;");
    headersWithDefaults.add("Electronic Format;");
    headersWithDefaults.add("Order Management Indivisible;");
    headersWithDefaults.add("Internal Orders Enabled;");
    headersWithDefaults.add("ATP Rule;");
    headersWithDefaults.add("Charge Periodicity;");
    headersWithDefaults.add("Customer Orders Enabled;");
    headersWithDefaults.add("Default Shipping Organization;");
    headersWithDefaults.add("Default Sales Order Source Type;");
    headersWithDefaults.add("Eligibility Rule;");
    headersWithDefaults.add("Financing Allowed;");
    headersWithDefaults.add("Internal Ordered;");
    headersWithDefaults.add("Picking Rule;");
    headersWithDefaults.add("Returnable;");
    headersWithDefaults.add("RMA Inspection Required;");
    headersWithDefaults.add("Sales Product Type;");
    headersWithDefaults.add("Back To Back Enabled;Y");
    headersWithDefaults.add("Shippable;Y");
    headersWithDefaults.add("Ship Model Complete;");
    headersWithDefaults.add("Order Management Transaction Enabled;Y");
    headersWithDefaults.add("Customer Ordered;");
    headersWithDefaults.add("Unit Weight;");
    headersWithDefaults.add("Weight Unit of Measure;");
    headersWithDefaults.add("Unit Volume;");
    headersWithDefaults.add("Volume Unit of Measure;");
    headersWithDefaults.add("Dimension Unit of Measure;");
    headersWithDefaults.add("Length;");
    headersWithDefaults.add("Width;");
    headersWithDefaults.add("Height;");
    headersWithDefaults.add("Collateral;");
    headersWithDefaults.add("Container;");
    headersWithDefaults.add("Container Type;");
    headersWithDefaults.add("Warehouse Equipment;");
    headersWithDefaults.add("Event;");
    headersWithDefaults.add("Internal Volume;");
    headersWithDefaults.add("Maximum Load Weight;");
    headersWithDefaults.add("Minimum Fill Percent;");
    headersWithDefaults.add("Vehicle;");
    headersWithDefaults.add("CAS Number;");
    headersWithDefaults.add("Hazardous Material;");
    headersWithDefaults.add("Process Costing Enabled;");
    headersWithDefaults.add("Process Execution Enabled;");
    headersWithDefaults.add("Process Quality Enabled;");
    headersWithDefaults.add("Process Supply Locator;");
    headersWithDefaults.add("Process Supply Subinventory;");
    headersWithDefaults.add("Process Yield Locator;");
    headersWithDefaults.add("Process Yield Subinventory;");
    headersWithDefaults.add("Recipe Enabled;");
    headersWithDefaults.add("Expense Account;");
    headersWithDefaults.add("UN Number;");
    headersWithDefaults.add("Unit of Issue;");
    headersWithDefaults.add("Rounding Factor;");
    headersWithDefaults.add("Receipt Close Tolerance Percentage;");
    headersWithDefaults.add("Input Tax Classification Code;10");
    headersWithDefaults.add("Purchased;Y");
    headersWithDefaults.add("Price Tolerance Percentage;");
    headersWithDefaults.add("Outsourced Assembly;");
    headersWithDefaults.add("Outside Processing Unit Type;");
    headersWithDefaults.add("Negotiation Required;");
    headersWithDefaults.add("Use Approved Supplier;");
    headersWithDefaults.add("Match Approval Level;");
    headersWithDefaults.add("Invoice Match Option;");
    headersWithDefaults.add("List Price;9.90");
    headersWithDefaults.add("Invoice Close Tolerance Percentage;");
    headersWithDefaults.add("Hazard Class;");
    headersWithDefaults.add("Default Buyer;");
    headersWithDefaults.add("Taxable;Y");
    headersWithDefaults.add("Purchasable;Y");
    headersWithDefaults.add("Outside Processing Item Enabled;");
    headersWithDefaults.add("Market Price;");
    headersWithDefaults.add("Asset Category;");
    headersWithDefaults.add("Allow Purchasing Document Description Update;");
    headersWithDefaults.add("Allow Express Transactions;");
    headersWithDefaults.add("Allow Substitute Receipts;");
    headersWithDefaults.add("Allow Unordered Receipts;");
    headersWithDefaults.add("Days Early Receipt Allowed;");
    headersWithDefaults.add("Days Late Receipt Allowed;");
    headersWithDefaults.add("Receipt Routing;");
    headersWithDefaults.add("Enforce Ship-to Location;");
    headersWithDefaults.add("Quantity Received Action;");
    headersWithDefaults.add("Quantity Received Tolerance;");
    headersWithDefaults.add("Receipt Date Exception Action;");
    headersWithDefaults.add("Create Fixed Asset;");
    headersWithDefaults.add("Service Start Type;");
    headersWithDefaults.add("Track in Installed Base;");
    headersWithDefaults.add("Enable for Customer Self Service;N");
    headersWithDefaults.add("Contract Item Type;");
    headersWithDefaults.add("StandardCoverage;");
    headersWithDefaults.add("Enable Defect Tracking;");
    headersWithDefaults.add("Instance Class;");
    headersWithDefaults.add("Billing Type;");
    headersWithDefaults.add("Recovered Part Disposition;");
    headersWithDefaults.add("Enable Contract Coverage;");
    headersWithDefaults.add("Starting Delay in Days;");
    headersWithDefaults.add("Service Duration;");
    headersWithDefaults.add("Service Duration Period;");
    headersWithDefaults.add("Service Request;");
    headersWithDefaults.add("Allow Suspend;");
    headersWithDefaults.add("Allow Terminate;");
    headersWithDefaults.add("Requires Fulfillment Location;");
    headersWithDefaults.add("Requires Item Association;");
    headersWithDefaults.add("Service Start Delay;");
    headersWithDefaults.add("Service Duration Type;");
    headersWithDefaults.add("Enable Provisioning;");
    headersWithDefaults.add("Enable Service Billing;");
    headersWithDefaults.add("Orderable on the Web;");
    headersWithDefaults.add("Back Orderable;");
    headersWithDefaults.add("Web Status;");
    headersWithDefaults.add("Minimum License Quantity;");
    headersWithDefaults.add("Build in WIP;");
    headersWithDefaults.add("Contract Manufacturing;");
    headersWithDefaults.add("WIP Supply Locator;");
    headersWithDefaults.add("WIP Supply Type;");
    headersWithDefaults.add("WIP Supply Subinventory;");
    headersWithDefaults.add("Overcompletion Tolerance Type;");
    headersWithDefaults.add("Overcompletion Tolerance Value;");
    headersWithDefaults.add("Inventory Carry Penalty;");
    headersWithDefaults.add("Operation Slack Penalty;");
    headersWithDefaults.add("Revision;");
    headersWithDefaults.add("Style Item;");
    headersWithDefaults.add("Style Item Number;");
    headersWithDefaults.add("Version Start Date;");
    headersWithDefaults.add("Version Revision Code;");
    headersWithDefaults.add("Version Label;");
    headersWithDefaults.add("Service Start Upon Milestone;");
    headersWithDefaults.add("Sales Product Sub Type;");
    headersWithDefaults.add("GLOBAL_ATTRIBUTE_CATEGORY;");
    headersWithDefaults.add("GLOBAL_ATTRIBUTE1;");
    headersWithDefaults.add("GLOBAL_ATTRIBUTE2;");
    headersWithDefaults.add("GLOBAL_ATTRIBUTE3;");
    headersWithDefaults.add("GLOBAL_ATTRIBUTE4;");
    headersWithDefaults.add("GLOBAL_ATTRIBUTE5;");
    headersWithDefaults.add("GLOBAL_ATTRIBUTE6;");
    headersWithDefaults.add("GLOBAL_ATTRIBUTE7;");
    headersWithDefaults.add("GLOBAL_ATTRIBUTE8;");
    headersWithDefaults.add("GLOBAL_ATTRIBUTE9;");
    headersWithDefaults.add("GLOBAL_ATTRIBUTE10;");
    headersWithDefaults.add("ATTRIBUTE_CATEGORY;Codici Prodotto");
    headersWithDefaults.add("ATTRIBUTE1;367058");
    headersWithDefaults.add("ATTRIBUTE2;0");
    headersWithDefaults.add("ATTRIBUTE3;A06AB06");
    headersWithDefaults.add("ATTRIBUTE4;");
    headersWithDefaults.add("ATTRIBUTE5;");
    headersWithDefaults.add("ATTRIBUTE6;");
    headersWithDefaults.add("ATTRIBUTE7;");
    headersWithDefaults.add("ATTRIBUTE8;");
    headersWithDefaults.add("ATTRIBUTE9;");
    headersWithDefaults.add("ATTRIBUTE10;");
    headersWithDefaults.add("ATTRIBUTE11;");
    headersWithDefaults.add("ATTRIBUTE12;");
    headersWithDefaults.add("ATTRIBUTE13;");
    headersWithDefaults.add("ATTRIBUTE14;");
    headersWithDefaults.add("ATTRIBUTE15;");
    headersWithDefaults.add("ATTRIBUTE16;");
    headersWithDefaults.add("ATTRIBUTE17;");
    headersWithDefaults.add("ATTRIBUTE18;");
    headersWithDefaults.add("ATTRIBUTE19;");
    headersWithDefaults.add("ATTRIBUTE20;");
    headersWithDefaults.add("ATTRIBUTE21;");
    headersWithDefaults.add("ATTRIBUTE22;");
    headersWithDefaults.add("ATTRIBUTE23;");
    headersWithDefaults.add("ATTRIBUTE24;");
    headersWithDefaults.add("ATTRIBUTE25;");
    headersWithDefaults.add("ATTRIBUTE26;");
    headersWithDefaults.add("ATTRIBUTE27;");
    headersWithDefaults.add("ATTRIBUTE28;");
    headersWithDefaults.add("ATTRIBUTE29;");
    headersWithDefaults.add("ATTRIBUTE30;");
    headersWithDefaults.add("ATTRIBUTE_NUMBER1;");
    headersWithDefaults.add("ATTRIBUTE_NUMBER2;");
    headersWithDefaults.add("ATTRIBUTE_NUMBER3;");
    headersWithDefaults.add("ATTRIBUTE_NUMBER4;");
    headersWithDefaults.add("ATTRIBUTE_NUMBER5;");
    headersWithDefaults.add("ATTRIBUTE_NUMBER6;");
    headersWithDefaults.add("ATTRIBUTE_NUMBER7;");
    headersWithDefaults.add("ATTRIBUTE_NUMBER8;");
    headersWithDefaults.add("ATTRIBUTE_NUMBER9;");
    headersWithDefaults.add("ATTRIBUTE_NUMBER10;");
    headersWithDefaults.add("ATTRIBUTE_DATE1;");
    headersWithDefaults.add("ATTRIBUTE_DATE2;");
    headersWithDefaults.add("ATTRIBUTE_DATE3;");
    headersWithDefaults.add("ATTRIBUTE_DATE4;");
    headersWithDefaults.add("ATTRIBUTE_DATE5;");
    headersWithDefaults.add("ATTRIBUTE_TIMESTAMP1;");
    headersWithDefaults.add("ATTRIBUTE_TIMESTAMP2;");
    headersWithDefaults.add("ATTRIBUTE_TIMESTAMP3;");
    headersWithDefaults.add("ATTRIBUTE_TIMESTAMP4;");
    headersWithDefaults.add("ATTRIBUTE_TIMESTAMP5;");
    headersWithDefaults.add("GLOBAL_ATTRIBUTE11;");
    headersWithDefaults.add("GLOBAL_ATTRIBUTE12;");
    headersWithDefaults.add("GLOBAL_ATTRIBUTE13;");
    headersWithDefaults.add("GLOBAL_ATTRIBUTE14;");
    headersWithDefaults.add("GLOBAL_ATTRIBUTE15;");
    headersWithDefaults.add("GLOBAL_ATTRIBUTE16;");
    headersWithDefaults.add("GLOBAL_ATTRIBUTE17;");
    headersWithDefaults.add("GLOBAL_ATTRIBUTE18;");
    headersWithDefaults.add("GLOBAL_ATTRIBUTE19;");
    headersWithDefaults.add("GLOBAL_ATTRIBUTE20;");
    headersWithDefaults.add("GLOBAL_ATTRIBUTE_NUMBER1;");
    headersWithDefaults.add("GLOBAL_ATTRIBUTE_NUMBER2;");
    headersWithDefaults.add("GLOBAL_ATTRIBUTE_NUMBER3;");
    headersWithDefaults.add("GLOBAL_ATTRIBUTE_NUMBER4;");
    headersWithDefaults.add("GLOBAL_ATTRIBUTE_NUMBER5;");
    headersWithDefaults.add("GLOBAL_ATTRIBUTE_DATE1;");
    headersWithDefaults.add("GLOBAL_ATTRIBUTE_DATE2;");
    headersWithDefaults.add("GLOBAL_ATTRIBUTE_DATE3;");
    headersWithDefaults.add("GLOBAL_ATTRIBUTE_DATE4;");
    headersWithDefaults.add("GLOBAL_ATTRIBUTE_DATE5;");
    headersWithDefaults.add("Procurement Business Unit;");
    headersWithDefaults.add("Enforce Purchasing Lead Time Flag;");
    headersWithDefaults.add("Replacement Type;");
    headersWithDefaults.add("Buyer Email Address;");
    headersWithDefaults.add("Default Expenditure Type;");
    headersWithDefaults.add("Hard Pegging Level;");
    headersWithDefaults.add("Allow Use of Common Supplies;");
    headersWithDefaults.add("Enable IoT;");
    headersWithDefaults.add("Packaging String;");
    
  }

  public static CsvOutputStream newInstance() throws Exception {
    initHeadersAndDefaults();
    CsvOutputStream csv = new CsvOutputStream();
    csv.setCrlf("\r\n");
    csv.setFieldSeparator(";");
    csv.setIntNumberFormat(null);
    csv.setStringFormat("\"%s\"", '"', '"');
    csv.setDoubleNumberFormat(NumberFormatFactory.newNumberFormat("###0.00",'.', '\''));
    csv.setHeadersWithDefaults(headersWithDefaults);
    csv.setDefault("Item Number", null);
    csv.setDefault("Description", null);
    csv.setDefault("Primary Unit of Measure", null);
    csv.setDefault("Pack Type", null);
    csv.setDefault("Long Description", null);
    csv.setDefault("Formatted Description", null);
    csv.setDefault("Input Tax Classification Code", null);
    csv.setDefault("List Price", null);
    csv.setDefault("ATTRIBUTE_CATEGORY", null);
    csv.setDefault("ATTRIBUTE1", null);
    csv.setDefault("ATTRIBUTE2", null);
    csv.setDefault("ATTRIBUTE3", null);
    csv.setIncludeHeader(false);
    return csv;
  }
}
