UPDATE FAI_FARMACLICK_FORNITORE 
SET 
 LAST_CSV=NULL
,LAST_CSV_FILENAME=NULL
,LAST_CSV_ZIPPED='N'
,LAST_CSV_DOWNLOAD_URL=NULL
,LAST_CSV_DOWNLOAD_AT_TS=NULL
,LAST_CSV_CONFIRM_URL=NULL
,LAST_CSV_CONFIRMED_AT_TS=NULL
,NO_LONGER_EXISTS_TS=SYSDATE
,ALL_DATA_STORED_TS=NULL
