MERGE INTO FAI_RECORD_L_LISTINO tgt
USING
(
SELECT
   ?OID_FORNITORE?              OID_FORNITORE
  ,?ALIQUOTA_IVA?               ALIQUOTA_IVA
  ,?ALLINEAM_SCADENZA?          ALLINEAM_SCADENZA
  ,?AZIONE?                     AZIONE
  ,?CATEGORIA_TIPO_PRODOTTO?    CATEGORIA_TIPO_PRODOTTO
  ,?CODICE_ADDEBITO?            CODICE_ADDEBITO
  ,?CODICE_CLIENTE?             CODICE_CLIENTE
  ,?CODICE_EAN?                 CODICE_EAN
  ,?CODICE_MINSAN?              CODICE_MINSAN
  ,?CODICE_PRODOTTO?            CODICE_PRODOTTO
  ,SYSDATE                      CREATION_TS
  ,?DESCR_PRODOTTO?             DESCR_PRODOTTO
  ,?DILAZ_PAGAM_GIORNI?         DILAZ_PAGAM_GIORNI
  ,?GIORNI_ABBU_CALC_ADD?       GIORNI_ABBU_CALC_ADD
  ,?PERC_ADDEBITO_AGG?          PERC_ADDEBITO_AGG
  ,?PERC_SC_PRZPUBDR_PRZNETUN?  PERC_SC_PRZPUBDR_PRZNETUN
  ,?PERC_SC_PRZPUB_PRZNETUN?    PERC_SC_PRZPUB_PRZNETUN
  ,?PERIODICITA_FATTURAZ?       PERIODICITA_FATTURAZ
  ,?PREZZO_AL_PUBBLICO?         PREZZO_AL_PUBBLICO
  ,?PREZZO_NETTO_UNITARIO?      PREZZO_NETTO_UNITARIO
  ,?PREZZO_PUBB_DERIVATO?       PREZZO_PUBB_DERIVATO
  ,?PREZZO_VEND_CONSIG?         PREZZO_VEND_CONSIG
  ,?PREZ_VEND_LIST_LORDO_SC?    PREZ_VEND_LIST_LORDO_SC
  ,?QUANT_PER_COLLO_VEND?       QUANT_PER_COLLO_VEND
  ,?SCONTO_1?                   SCONTO_1
  ,?SCONTO_2?                   SCONTO_2
  ,?SCONTO_CASSA?               SCONTO_CASSA
  ,?SOMMA_SCONTO_1_2?           SOMMA_SCONTO_1_2
  ,SYSDATE                      UPDATE_TS
FROM DUAL
) src
ON (tgt.OID_FORNITORE=src.OID_FORNITORE AND tgt.CODICE_CLIENTE=src.CODICE_CLIENTE AND tgt.CODICE_PRODOTTO=src.CODICE_PRODOTTO)
WHEN MATCHED
THEN UPDATE SET
   tgt.ALIQUOTA_IVA              = src.ALIQUOTA_IVA
  ,tgt.ALLINEAM_SCADENZA         = src.ALLINEAM_SCADENZA
  ,tgt.AZIONE                    = src.AZIONE
  ,tgt.CATEGORIA_TIPO_PRODOTTO   = src.CATEGORIA_TIPO_PRODOTTO
  ,tgt.CODICE_ADDEBITO           = src.CODICE_ADDEBITO
  ,tgt.CODICE_EAN                = src.CODICE_EAN
  ,tgt.CODICE_MINSAN             = src.CODICE_MINSAN
  ,tgt.DESCR_PRODOTTO            = src.DESCR_PRODOTTO
  ,tgt.DILAZ_PAGAM_GIORNI        = src.DILAZ_PAGAM_GIORNI
  ,tgt.GIORNI_ABBU_CALC_ADD      = src.GIORNI_ABBU_CALC_ADD
  ,tgt.PERC_ADDEBITO_AGG         = src.PERC_ADDEBITO_AGG
  ,tgt.PERC_SC_PRZPUBDR_PRZNETUN = src.PERC_SC_PRZPUBDR_PRZNETUN
  ,tgt.PERC_SC_PRZPUB_PRZNETUN   = src.PERC_SC_PRZPUB_PRZNETUN
  ,tgt.PERIODICITA_FATTURAZ      = src.PERIODICITA_FATTURAZ
  ,tgt.PREZZO_AL_PUBBLICO        = src.PREZZO_AL_PUBBLICO
  ,tgt.PREZZO_NETTO_UNITARIO     = src.PREZZO_NETTO_UNITARIO
  ,tgt.PREZZO_PUBB_DERIVATO      = src.PREZZO_PUBB_DERIVATO
  ,tgt.PREZZO_VEND_CONSIG        = src.PREZZO_VEND_CONSIG
  ,tgt.PREZ_VEND_LIST_LORDO_SC   = src.PREZ_VEND_LIST_LORDO_SC
  ,tgt.QUANT_PER_COLLO_VEND      = src.QUANT_PER_COLLO_VEND
  ,tgt.SCONTO_1                  = src.SCONTO_1
  ,tgt.SCONTO_2                  = src.SCONTO_2
  ,tgt.SCONTO_CASSA              = src.SCONTO_CASSA
  ,tgt.SOMMA_SCONTO_1_2          = src.SOMMA_SCONTO_1_2
  ,tgt.UPDATE_TS                 = src.UPDATE_TS
WHEN NOT MATCHED
THEN INSERT
(
   OID
  ,OID_FORNITORE
  ,ALIQUOTA_IVA
  ,ALLINEAM_SCADENZA
  ,AZIONE
  ,CATEGORIA_TIPO_PRODOTTO
  ,CODICE_ADDEBITO
  ,CODICE_CLIENTE
  ,CODICE_EAN
  ,CODICE_MINSAN
  ,CODICE_PRODOTTO
  ,CREATION_TS
  ,DESCR_PRODOTTO
  ,DILAZ_PAGAM_GIORNI
  ,GIORNI_ABBU_CALC_ADD
  ,PERC_ADDEBITO_AGG
  ,PERC_SC_PRZPUBDR_PRZNETUN
  ,PERC_SC_PRZPUB_PRZNETUN
  ,PERIODICITA_FATTURAZ
  ,PREZZO_AL_PUBBLICO
  ,PREZZO_NETTO_UNITARIO
  ,PREZZO_PUBB_DERIVATO
  ,PREZZO_VEND_CONSIG
  ,PREZ_VEND_LIST_LORDO_SC
  ,QUANT_PER_COLLO_VEND
  ,SCONTO_1
  ,SCONTO_2
  ,SCONTO_CASSA
  ,SOMMA_SCONTO_1_2
  ,UPDATE_TS
)
VALUES
(
   OID.NEXTVAL
  ,src.OID_FORNITORE
  ,src.ALIQUOTA_IVA
  ,src.ALLINEAM_SCADENZA
  ,src.AZIONE
  ,src.CATEGORIA_TIPO_PRODOTTO
  ,src.CODICE_ADDEBITO
  ,src.CODICE_CLIENTE
  ,src.CODICE_EAN
  ,src.CODICE_MINSAN
  ,src.CODICE_PRODOTTO
  ,src.CREATION_TS
  ,src.DESCR_PRODOTTO
  ,src.DILAZ_PAGAM_GIORNI
  ,src.GIORNI_ABBU_CALC_ADD
  ,src.PERC_ADDEBITO_AGG
  ,src.PERC_SC_PRZPUBDR_PRZNETUN
  ,src.PERC_SC_PRZPUB_PRZNETUN
  ,src.PERIODICITA_FATTURAZ
  ,src.PREZZO_AL_PUBBLICO
  ,src.PREZZO_NETTO_UNITARIO
  ,src.PREZZO_PUBB_DERIVATO
  ,src.PREZZO_VEND_CONSIG
  ,src.PREZ_VEND_LIST_LORDO_SC
  ,src.QUANT_PER_COLLO_VEND
  ,src.SCONTO_1
  ,src.SCONTO_2
  ,src.SCONTO_CASSA
  ,src.SOMMA_SCONTO_1_2
  ,src.UPDATE_TS
)
