UPDATE FAI_APPROVVIGIONAMENTO_FARMACO
SET CODICE_MINSAN     = ?
  , CODICE_EAN        = ?
  , OID_FORNITORE     = ?
  , QUANTITA          = ?
  , OID_STATUS        = ?
  , STATUS_DESCR      = ?
  , STATUS_TECH_DESCR = ?
  , STATUS_UPDATED_TS = ?

WHERE OID = ?
