UPDATE FAI_IMPORT_CONFIG 
SET 
	 LAST_RUN_START_TS = ?LAST_RUN_START_TS?
	,LAST_RUN_END_TS = NULL
	,LAST_RUN_TYPE = ?LAST_RUN_TYPE?
	,LAST_RUN_DONE = 'N'
	,LAST_RUN_DESCR = NULL
WHERE
    OID = ?OID?
