ALTER TABLE FAI_APPROVVIGIONAMENTO_FARMACO ADD CODICE_SOSTITUITO_MINSAN VARCHAR2(9);
ALTER TABLE FAI_ORDINE_OUT ADD REQUEST_XML CLOB;
ALTER TABLE FAI_ORDINE_OUT ADD RESPONSE_XML CLOB;
ALTER TABLE FAI_UPLOAD_TASK DROP CONSTRAINT FK_UPLODTASK_STATUS;
DROP TABLE FAI_UPLOAD_CSV_STATUS;
ALTER TABLE FAI_GENERIC_TASK ADD STATUS_DESCR CLOB;
ALTER TABLE FAI_GENERIC_TASK ADD STATUS_TECH_DESCR CLOB;