	--
-- FAI_ITEM_STATUS
--


INSERT INTO FAI_ITEM_STATUS (OID, ACRONYM, DESCR)
      SELECT 1 ,'TO PROCESS','TO PROCESS'
      FROM (SELECT COUNT(*) CNT FROM FAI_ITEM_STATUS WHERE ACRONYM = 'TO PROCESS')
      T WHERE CNT = 0;
      
INSERT INTO FAI_ITEM_STATUS (OID, ACRONYM, DESCR)
      SELECT 2 ,'PROCESSING','PROCESSING'
      FROM (SELECT COUNT(*) CNT FROM FAI_ITEM_STATUS WHERE ACRONYM = 'PROCESSING')
      T WHERE CNT = 0;

INSERT INTO FAI_ITEM_STATUS (OID, ACRONYM, DESCR)
      SELECT 3 ,'PROCESSED','PROCESSED'
      FROM (SELECT COUNT(*) CNT FROM FAI_ITEM_STATUS WHERE ACRONYM = 'PROCESSED')
      T WHERE CNT = 0;
      
INSERT INTO FAI_ITEM_STATUS (OID, ACRONYM, DESCR)
      SELECT 4 ,'ERROR','ERROR'
      FROM (SELECT COUNT(*) CNT FROM FAI_ITEM_STATUS WHERE ACRONYM = 'ERROR')
      T WHERE CNT = 0;

INSERT INTO FAI_ITEM_STATUS (OID, ACRONYM, DESCR)
      SELECT 5 ,'SUSPENDED','SUSPENDED'
      FROM (SELECT COUNT(*) CNT FROM FAI_ITEM_STATUS WHERE ACRONYM = 'SUSPENDED')
      T WHERE CNT = 0;

INSERT INTO FAI_ITEM_STATUS (OID, ACRONYM, DESCR)
      SELECT 6 ,'TO APPROVE','TO APPROVE'
      FROM (SELECT COUNT(*) CNT FROM FAI_ITEM_STATUS WHERE ACRONYM = 'TO APPROVE')
      T WHERE CNT = 0;

INSERT INTO FAI_ITEM_STATUS (OID, ACRONYM, DESCR)
      SELECT 7 ,'APPROVED','APPROVED'
      FROM (SELECT COUNT(*) CNT FROM FAI_ITEM_STATUS WHERE ACRONYM = 'APPROVED')
      T WHERE CNT = 0;

INSERT INTO FAI_ITEM_STATUS (OID, ACRONYM, DESCR)
      SELECT 8 ,'VOIDED','VOIDED'
      FROM (SELECT COUNT(*) CNT FROM FAI_ITEM_STATUS WHERE ACRONYM = 'VOIDED')
      T WHERE CNT = 0;
	  
	  
INSERT INTO FAI_ITEM_STATUS (OID, ACRONYM, DESCR)
      SELECT 9 ,'FULLFILLED','FULLFILLED'
      FROM (SELECT COUNT(*) CNT FROM FAI_ITEM_STATUS WHERE ACRONYM = 'FULLFILLED')
      T WHERE CNT = 0;


--
-- FAI_TIPO_FARMACO
--      
      
INSERT INTO FAI_TIPO_FARMACO (OID, ACRONYM, DESCR)
      SELECT 1 ,'FARMACO', 'FARMACO'
      FROM (SELECT COUNT(*) CNT FROM FAI_TIPO_FARMACO WHERE ACRONYM = 'FARMACO')
      T WHERE CNT = 0;

INSERT INTO FAI_TIPO_FARMACO (OID, ACRONYM, DESCR)
      SELECT 2 ,'PARAFARMACO', 'PARAFARMACO'
      FROM (SELECT COUNT(*) CNT FROM FAI_TIPO_FARMACO WHERE ACRONYM = 'PARAFARMACO')
      T WHERE CNT = 0;



--
-- FAI_UPLOAD_CSV_STATUS
--


INSERT INTO FAI_UPLOAD_CSV_STATUS (OID, ACRONYM, DESCR)
      SELECT 1 ,'TO PROCESS','ESEGUIRE'
      FROM (SELECT COUNT(*) CNT FROM FAI_UPLOAD_CSV_STATUS WHERE ACRONYM = 'TO PROCESS')
      T WHERE CNT = 0;
      
INSERT INTO FAI_UPLOAD_CSV_STATUS (OID, ACRONYM, DESCR)
      SELECT 2 ,'PROCESSING','IN CORSO'
      FROM (SELECT COUNT(*) CNT FROM FAI_UPLOAD_CSV_STATUS WHERE ACRONYM = 'PROCESSING')
      T WHERE CNT = 0;

INSERT INTO FAI_UPLOAD_CSV_STATUS (OID, ACRONYM, DESCR)
      SELECT 3 ,'PROCESSED','COMPLETATO'
      FROM (SELECT COUNT(*) CNT FROM FAI_UPLOAD_CSV_STATUS WHERE ACRONYM = 'PROCESSED')
      T WHERE CNT = 0;
      
INSERT INTO FAI_UPLOAD_CSV_STATUS (OID, ACRONYM, DESCR)
      SELECT 4 ,'ERROR','ANNULATO'
      FROM (SELECT COUNT(*) CNT FROM FAI_UPLOAD_CSV_STATUS WHERE ACRONYM = 'ERROR')
      T WHERE CNT = 0;
	  
	  
	  
   INSERT INTO FAI_UPLOAD_TASK_PROPERTY
("OID", "KEY", VALUE)
 SELECT 1, 'csvUploadRootDir', TO_CLOB('G:\FAI\docs')
      FROM (SELECT COUNT(*) CNT FROM FAI_UPLOAD_TASK_PROPERTY WHERE KEY = 'csvUploadRootDir')
	    T WHERE CNT = 0;

INSERT INTO FAI_FORNITORE (OID,CODICE,CODICE_FARMACLICK,SUPPLIERSERVICE_CLASS_NAME) values (12,'FaiRnd0002','FaiRnd0002','fai.broker.supplier.driver.fake.FakeSupplierService');
INSERT INTO FAI_FORNITORE (OID,CODICE,CODICE_FARMACLICK,SUPPLIERSERVICE_CLASS_NAME) values (9,'DEMO03','DEMO03','fai.broker.supplier.driver.farmaclick.FarmaclickSupplierService');
INSERT INTO FAI_FORNITORE (OID,CODICE,CODICE_FARMACLICK,SUPPLIERSERVICE_CLASS_NAME) values (11,'FaiRnd0001','FaiRnd0001','fai.broker.supplier.driver.comifar.ComifarSupplierService');


INSERT INTO FAI_FORNITORE_CALENDAR ("OID",OID_FORNITORE,DATE_OF_WEEK,HOUR_START,HOUR_END) VALUES (1,9,1,TIMESTAMP '2021-11-24 00:00:00.000000',TIMESTAMP '2021-11-24 23:59:59.000000');
INSERT INTO FAI_FORNITORE_CALENDAR ("OID",OID_FORNITORE,DATE_OF_WEEK,HOUR_START,HOUR_END) VALUES (2,11,1,TIMESTAMP '2021-11-24 00:00:00.000000',TIMESTAMP '2021-11-24 23:59:59.000000');
INSERT INTO FAI_FORNITORE_CALENDAR ("OID",OID_FORNITORE,DATE_OF_WEEK,HOUR_START,HOUR_END) VALUES (3,9,2,TIMESTAMP '2021-11-24 00:00:00.000000',TIMESTAMP '2021-11-24 23:59:59.000000');
INSERT INTO FAI_FORNITORE_CALENDAR ("OID",OID_FORNITORE,DATE_OF_WEEK,HOUR_START,HOUR_END) VALUES (4,11,2,TIMESTAMP '2021-11-24 00:00:00.000000',TIMESTAMP '2021-11-24 23:59:59.000000');
INSERT INTO FAI_FORNITORE_CALENDAR ("OID",OID_FORNITORE,DATE_OF_WEEK,HOUR_START,HOUR_END) VALUES (5,9,3,TIMESTAMP '2021-11-24 00:00:00.000000',TIMESTAMP '2021-11-24 23:59:59.000000');
INSERT INTO FAI_FORNITORE_CALENDAR ("OID",OID_FORNITORE,DATE_OF_WEEK,HOUR_START,HOUR_END) VALUES (6,11,3,TIMESTAMP '2021-11-24 00:00:00.000000',TIMESTAMP '2021-11-24 23:59:59.000000');
INSERT INTO FAI_FORNITORE_CALENDAR ("OID",OID_FORNITORE,DATE_OF_WEEK,HOUR_START,HOUR_END) VALUES (7,9,4,TIMESTAMP '2021-11-24 00:00:00.000000',TIMESTAMP '2021-11-24 23:59:59.000000');
INSERT INTO FAI_FORNITORE_CALENDAR ("OID",OID_FORNITORE,DATE_OF_WEEK,HOUR_START,HOUR_END) VALUES (8,11,4,TIMESTAMP '2021-11-24 00:00:00.000000',TIMESTAMP '2021-11-24 23:59:59.000000');
INSERT INTO FAI_FORNITORE_CALENDAR ("OID",OID_FORNITORE,DATE_OF_WEEK,HOUR_START,HOUR_END) VALUES (9,9,5,TIMESTAMP '2021-11-24 00:00:00.000000',TIMESTAMP '2021-11-24 23:59:59.000000');
INSERT INTO FAI_FORNITORE_CALENDAR ("OID",OID_FORNITORE,DATE_OF_WEEK,HOUR_START,HOUR_END) VALUES (10,11,5,TIMESTAMP '2021-11-24 00:00:00.000000',TIMESTAMP '2021-11-24 23:59:59.000000');
INSERT INTO FAI_FORNITORE_CALENDAR ("OID",OID_FORNITORE,DATE_OF_WEEK,HOUR_START,HOUR_END) VALUES (11,9,6,TIMESTAMP '2021-11-24 00:00:00.000000',TIMESTAMP '2021-11-24 23:59:59.000000');
INSERT INTO FAI_FORNITORE_CALENDAR ("OID",OID_FORNITORE,DATE_OF_WEEK,HOUR_START,HOUR_END) VALUES (12,11,6,TIMESTAMP '2021-11-24 00:00:00.000000',TIMESTAMP '2021-11-24 23:59:59.000000');
INSERT INTO FAI_FORNITORE_CALENDAR ("OID",OID_FORNITORE,DATE_OF_WEEK,HOUR_START,HOUR_END) VALUES (13,9,7,TIMESTAMP '2021-11-24 00:00:00.000000',TIMESTAMP '2021-11-24 23:59:59.000000');
INSERT INTO FAI_FORNITORE_CALENDAR ("OID",OID_FORNITORE,DATE_OF_WEEK,HOUR_START,HOUR_END) VALUES (14,11,7,TIMESTAMP '2021-11-24 00:00:00.000000',TIMESTAMP '2021-11-24 23:59:59.000000');



INSERT INTO FAI_IMPORT_CONFIG
   (OID, ACRONYM, SERVICE_LOGIN, SERVICE_PASS, SERVICE_PASS_ENCR, 
    SERVICE_QUERY_TIME, SERVICE_QUERY_SMTWTFS, SERVICE_QUERY_URL, SERVICE_RESUME_PREV_SESS, LAST_RUN_END_TS, 
    LAST_RUN_TYPE, LAST_RUN_DONE, CLASS_NAME, SERVICE_QUERY_ZIPPED_CONTENT,SERVICE_API_LEVEL,OID_FORNITORE)
 VALUES
   (2, 'FARMACLICK', 'FCK00042794', 'KLyQD+K31DEc5HDIasdgiat6FQHuUh7Gr9cotQblUNHvQZTKLUooUm861qhbEZHYJ9WS1lWd8uZUbl9seWFoMQ==', 'S', 
    TO_DATE('01/01/1970 00:45:00', 'MM/DD/YYYY HH24:MI:SS'), 'CCCCCCC', 'https://secure.infarmaclick.com/public_server_pro/Farmaclick2010001FCKLogin', 'S', TO_DATE('06/01/2021 12:13:47', 'MM/DD/YYYY HH24:MI:SS'), 
    'C', 'S', 'farmaclick.task.FarmaclickDataCollector', 'S', '2005.001',9);
INSERT INTO FAI_IMPORT_CONFIG
   (OID, ACRONYM, SERVICE_LOGIN, SERVICE_PASS, SERVICE_PASS_ENCR, 
    SERVICE_QUERY_TIME, SERVICE_QUERY_SMTWTFS, SERVICE_QUERY_URL, SERVICE_RESUME_PREV_SESS, LAST_RUN_END_TS, 
    LAST_RUN_TYPE, LAST_RUN_DONE, CLASS_NAME, SERVICE_QUERY_ZIPPED_CONTENT)
 VALUES
   (3, 'FARMADATI', 'BDF250035w', 'u/w6SSKTNwa0d+B+9cuMJ5FzksCyuXgnOrh0V5qbsSpyEbe86mpMoxcPEJKOOUnklFZqVJ9sK8oHh4A+AMwAxg==', 'S', 
    TO_DATE('01/01/1970 02:45:00', 'MM/DD/YYYY HH24:MI:SS'), 'CCCCCCC', 'https://webservices.farmadati.it/WS2S/FarmadatiItaliaWebServicesM2.svc', 'S', TO_DATE('05/22/2021 01:13:22', 'MM/DD/YYYY HH24:MI:SS'), 
    'C', 'S', 'farmadati.task.FarmadatiDataCollector', 'S');
	
	INSERT INTO FAI_IMPORT_CONFIG ("OID",ACRONYM,DESCR,SERVICE_LOGIN,SERVICE_PASS,SERVICE_PASS_ENCR,
SERVICE_QUERY_TIME,SERVICE_QUERY_SMTWTFS,SERVICE_QUERY_URL,SERVICE_RESUME_PREV_SESS,LAST_RUN_START_TS,
LAST_RUN_END_TS,LAST_RUN_TYPE,LAST_RUN_DONE,LAST_RUN_DESCR,CLASS_NAME,SERVICE_QUERY_ZIPPED_CONTENT,
SERVICE_PASS_SECOND_LEVEL,OID_FORNITORE) VALUES (15,'COMIFAR',NULL,'288752','bEJQ4+1OrY5f5Liaur3lVdR4uE0P9VJH5EpfoK+HdFyfTrN/YWT7b8JQHzgHXeQ953tHgkj7z6QCYbI3e7V+DQ==','S',TIMESTAMP '1970-01-01 00:00:00.000000','CCCCCCC','https://ordiniwebtest.comifar.it','S',NULL,NULL,NULL,NULL,NULL,'comifar.task.ComifarDataCollector','S','McwFFtbiVStw9i10h92Tk1JpjEpYpuDkKG4IUDZVn/BaTqk/FdNLYCh9d1EXJ212sbcvWdFkQh+JoZLZHFPxPQ==',11);



--
-- commit
--      
commit;
              
			  
			  