SET DEFINE OFF;
Insert into FAI.FAI_IMPORT_CONFIG
   (OID, ACRONYM, SERVICE_LOGIN, SERVICE_PASS, SERVICE_PASS_ENCR, 
    SERVICE_QUERY_TIME, SERVICE_QUERY_SMTWTFS, SERVICE_QUERY_URL, SERVICE_RESUME_PREV_SESS, LAST_RUN_END_TS, 
    LAST_RUN_TYPE, LAST_RUN_DONE, CLASS_NAME, SERVICE_QUERY_ZIPPED_CONTENT)
 Values
   (2, 'FARMACLICK', 'FCK00042794', 'KLyQD+K31DEc5HDIasdgiat6FQHuUh7Gr9cotQblUNHvQZTKLUooUm861qhbEZHYJ9WS1lWd8uZUbl9seWFoMQ==', 'S', 
    TO_DATE('01/01/1970 00:45:00', 'MM/DD/YYYY HH24:MI:SS'), 'CCCCCCC', 'https://secure.infarmaclick.com/public_server_pro/Farmaclick2010001FCKLogin', 'S', TO_DATE('06/01/2021 12:13:47', 'MM/DD/YYYY HH24:MI:SS'), 
    'C', 'S', 'farmaclick.task.FarmaclickDataCollector', 'S');
Insert into FAI.FAI_IMPORT_CONFIG
   (OID, ACRONYM, SERVICE_LOGIN, SERVICE_PASS, SERVICE_PASS_ENCR, 
    SERVICE_QUERY_TIME, SERVICE_QUERY_SMTWTFS, SERVICE_QUERY_URL, SERVICE_RESUME_PREV_SESS, LAST_RUN_END_TS, 
    LAST_RUN_TYPE, LAST_RUN_DONE, CLASS_NAME, SERVICE_QUERY_ZIPPED_CONTENT)
 Values
   (3, 'FARMADATI', 'BDF250035w', 'u/w6SSKTNwa0d+B+9cuMJ5FzksCyuXgnOrh0V5qbsSpyEbe86mpMoxcPEJKOOUnklFZqVJ9sK8oHh4A+AMwAxg==', 'S', 
    TO_DATE('01/01/1970 02:45:00', 'MM/DD/YYYY HH24:MI:SS'), 'CCCCCCC', 'https://webservices.farmadati.it/WS2S/FarmadatiItaliaWebServicesM2.svc', 'S', TO_DATE('05/22/2021 01:13:22', 'MM/DD/YYYY HH24:MI:SS'), 
    'C', 'S', 'farmadati.task.FarmadatiDataCollector', 'S');
COMMIT;
