CREATE USER FAI IDENTIFIED BY FAI
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT ALTER ANY INDEX TO FAI;

GRANT ALTER ANY MATERIALIZED VIEW TO FAI;

GRANT ALTER ANY PROCEDURE TO FAI;

GRANT ALTER ANY SEQUENCE TO FAI;

GRANT ALTER ANY TABLE TO FAI;

GRANT ALTER ANY TRIGGER TO FAI;

GRANT ALTER DATABASE TO FAI;

GRANT ALTER SESSION TO FAI;

GRANT ALTER SYSTEM TO FAI;

GRANT ALTER TABLESPACE TO FAI;

GRANT ALTER USER TO FAI;

GRANT ANALYZE ANY TO FAI;

GRANT ANALYZE ANY DICTIONARY TO FAI;

GRANT COMMENT ANY TABLE TO FAI;

GRANT CREATE ANY CONTEXT TO FAI;

GRANT CREATE ANY INDEX TO FAI;

GRANT CREATE ANY JOB TO FAI;

GRANT CREATE ANY MATERIALIZED VIEW TO FAI;

GRANT CREATE ANY PROCEDURE TO FAI;

GRANT CREATE ANY SEQUENCE TO FAI;

GRANT CREATE ANY SYNONYM TO FAI;

GRANT CREATE ANY TABLE TO FAI;

GRANT CREATE ANY TRIGGER TO FAI;

GRANT CREATE ANY TYPE TO FAI;

GRANT CREATE ANY VIEW TO FAI;

GRANT CREATE JOB TO FAI;

GRANT CREATE MATERIALIZED VIEW TO FAI;

GRANT CREATE PROCEDURE TO FAI;

GRANT CREATE SEQUENCE TO FAI;

GRANT CREATE SESSION TO FAI;

GRANT CREATE SYNONYM TO FAI;

GRANT CREATE TABLE TO FAI;

GRANT CREATE TABLESPACE TO FAI;

GRANT CREATE TRIGGER TO FAI;

GRANT CREATE USER TO FAI;

GRANT CREATE VIEW TO FAI;

GRANT DEBUG ANY PROCEDURE TO FAI;

GRANT DEBUG CONNECT SESSION TO FAI;

GRANT DELETE ANY TABLE TO FAI;

GRANT DROP ANY CONTEXT TO FAI;

GRANT DROP ANY INDEX TO FAI;

GRANT DROP ANY MATERIALIZED VIEW TO FAI;

GRANT DROP ANY PROCEDURE TO FAI;

GRANT DROP ANY ROLE TO FAI;

GRANT DROP ANY SEQUENCE TO FAI;

GRANT DROP ANY TABLE TO FAI;

GRANT DROP ANY TRIGGER TO FAI;

GRANT DROP ANY TYPE TO FAI;

GRANT DROP ANY VIEW TO FAI;

GRANT DROP TABLESPACE TO FAI;

GRANT EXECUTE ANY PROCEDURE TO FAI;

GRANT EXECUTE ANY TYPE TO FAI;

GRANT GRANT ANY PRIVILEGE TO FAI;

GRANT GRANT ANY ROLE TO FAI;

GRANT IMPORT FULL DATABASE TO FAI;

GRANT INSERT ANY TABLE TO FAI;

GRANT LOCK ANY TABLE TO FAI;

GRANT MANAGE FILE GROUP TO FAI;

GRANT MANAGE TABLESPACE TO FAI;

GRANT MERGE ANY VIEW TO FAI;

GRANT SELECT ANY DICTIONARY TO FAI;

GRANT SELECT ANY SEQUENCE TO FAI;

GRANT SELECT ANY TABLE TO FAI;

GRANT SELECT ANY TRANSACTION TO FAI;

GRANT UNDER ANY TABLE TO FAI;

GRANT UNDER ANY TYPE TO FAI;

GRANT UNDER ANY VIEW TO FAI;

GRANT UNLIMITED TABLESPACE TO FAI;

GRANT UPDATE ANY TABLE TO FAI;CREATE USER FAI IDENTIFIED BY FAI1
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT ALTER ANY INDEX TO FAI;

GRANT ALTER ANY MATERIALIZED VIEW TO FAI;

GRANT ALTER ANY PROCEDURE TO FAI;

GRANT ALTER ANY SEQUENCE TO FAI;

GRANT ALTER ANY TABLE TO FAI;

GRANT ALTER ANY TRIGGER TO FAI;

GRANT ALTER DATABASE TO FAI;

GRANT ALTER SESSION TO FAI;

GRANT ALTER SYSTEM TO FAI;

GRANT ALTER TABLESPACE TO FAI;

GRANT ALTER USER TO FAI;

GRANT ANALYZE ANY TO FAI;

GRANT ANALYZE ANY DICTIONARY TO FAI;

GRANT COMMENT ANY TABLE TO FAI;

GRANT CREATE ANY CONTEXT TO FAI;

GRANT CREATE ANY INDEX TO FAI;

GRANT CREATE ANY JOB TO FAI;

GRANT CREATE ANY MATERIALIZED VIEW TO FAI;

GRANT CREATE ANY PROCEDURE TO FAI;

GRANT CREATE ANY SEQUENCE TO FAI;

GRANT CREATE ANY SYNONYM TO FAI;

GRANT CREATE ANY TABLE TO FAI;

GRANT CREATE ANY TRIGGER TO FAI;

GRANT CREATE ANY TYPE TO FAI;

GRANT CREATE ANY VIEW TO FAI;

GRANT CREATE JOB TO FAI;

GRANT CREATE MATERIALIZED VIEW TO FAI;

GRANT CREATE PROCEDURE TO FAI;

GRANT CREATE SEQUENCE TO FAI;

GRANT CREATE SESSION TO FAI;

GRANT CREATE SYNONYM TO FAI;

GRANT CREATE TABLE TO FAI;

GRANT CREATE TABLESPACE TO FAI;

GRANT CREATE TRIGGER TO FAI;

GRANT CREATE USER TO FAI;

GRANT CREATE VIEW TO FAI;

GRANT DEBUG ANY PROCEDURE TO FAI;

GRANT DEBUG CONNECT SESSION TO FAI;

GRANT DELETE ANY TABLE TO FAI;

GRANT DROP ANY CONTEXT TO FAI;

GRANT DROP ANY INDEX TO FAI;

GRANT DROP ANY MATERIALIZED VIEW TO FAI;

GRANT DROP ANY PROCEDURE TO FAI;

GRANT DROP ANY ROLE TO FAI;

GRANT DROP ANY SEQUENCE TO FAI;

GRANT DROP ANY TABLE TO FAI;

GRANT DROP ANY TRIGGER TO FAI;

GRANT DROP ANY TYPE TO FAI;

GRANT DROP ANY VIEW TO FAI;

GRANT DROP TABLESPACE TO FAI;

GRANT EXECUTE ANY PROCEDURE TO FAI;

GRANT EXECUTE ANY TYPE TO FAI;

GRANT GRANT ANY PRIVILEGE TO FAI;

GRANT GRANT ANY ROLE TO FAI;

GRANT IMPORT FULL DATABASE TO FAI;

GRANT INSERT ANY TABLE TO FAI;

GRANT LOCK ANY TABLE TO FAI;

GRANT MANAGE FILE GROUP TO FAI;

GRANT MANAGE TABLESPACE TO FAI;

GRANT MERGE ANY VIEW TO FAI;

GRANT SELECT ANY DICTIONARY TO FAI;

GRANT SELECT ANY SEQUENCE TO FAI;

GRANT SELECT ANY TABLE TO FAI;

GRANT SELECT ANY TRANSACTION TO FAI;

GRANT UNDER ANY TABLE TO FAI;

GRANT UNDER ANY TYPE TO FAI;

GRANT UNDER ANY VIEW TO FAI;

GRANT UNLIMITED TABLESPACE TO FAI;

GRANT UPDATE ANY TABLE TO FAI;