CREATE OR REPLACE VIEW V_FAI_LISTINI_FORNITORI 
AS 
SELECT
   'FARMACLICK'                                   FONTE
  ,FAI_FARMACLICK_FORNITORE.CODICE                CODICE_FORNITORE_FONTE
  ,FAI_FORNITORE.CODICE                           CODICE_FORNITORE
  ,FAI_FORNITORE.OID                              OID_FORNITORE
  ,NVL(LISTINO.CODICE_MINSAN, LISTINO.CODICE_EAN) CODICE
  ,LISTINO.CODICE_MINSAN                          CODICE_MINSAN  
  ,LISTINO.CODICE_EAN                             CODICE_EAN     
  ,LISTINO.DESCR_PRODOTTO                         DESCRIZIONE
  ,LISTINO.ALIQUOTA_IVA                           ALIQUOTA_IVA
  ,LISTINO.PREZ_VEND_LIST_LORDO_SC                PREZZO_LORDO_SCONTI
  ,ROUND(LISTINO.PREZ_VEND_LIST_LORDO_SC * (1 + ALIQUOTA_IVA/100)                           , 2)    PREZZO_LORDO_SCONTI_IVATO
  ,ROUND(LISTINO.PREZ_VEND_LIST_LORDO_SC * (1-SOMMA_SCONTO_1_2/100)                         , 2)    PREZZO
  ,ROUND(LISTINO.PREZ_VEND_LIST_LORDO_SC * (1 + ALIQUOTA_IVA/100) * (1-SOMMA_SCONTO_1_2/100), 2)    PREZZO_IVATO
FROM 
   FAI_FORNITORE
  ,FAI_FARMACLICK_FORNITORE 
  ,FAI_RECORD_L_LISTINO LISTINO
WHERE  
   FAI_FORNITORE.CODICE_FARMACLICK= FAI_FARMACLICK_FORNITORE.CODICE
   AND
   FAI_FARMACLICK_FORNITORE.OID = LISTINO.OID_FORNITORE
UNION
SELECT
   'COMIFAR'                                   FONTE
  ,FAI_COMIFAR_LISTINO.CODICE_CLIENTE          CODICE_FORNITORE_FONTE
  ,FAI_FORNITORE.CODICE                        CODICE_FORNITORE
  ,FAI_FORNITORE.OID                           OID_FORNITORE
  ,FAI_COMIFAR_LISTINO.CODICE_MINSAN           CODICE
  ,FAI_COMIFAR_LISTINO.CODICE_MINSAN           CODICE_MINSAN  
  ,''                                          CODICE_EAN     
  ,FAI_COMIFAR_LISTINO.NOTA_PRODOTTO           DESCRIZIONE
  ,FAI_COMIFAR_LISTINO.ALIQUOTA_IVA            ALIQUOTA_IVA
  ,FAI_COMIFAR_LISTINO.SCONTO                  PREZZO_LORDO_SCONTI
  ,NULL                                        PREZZO_LORDO_SCONTI_IVATO
  ,FAI_COMIFAR_LISTINO_PRICE.PREZZO_NETTO      PREZZO
  ,NULL                                        PREZZO_IVATO
FROM 
	FAI_FORNITORE,
    FAI_COMIFAR_LISTINO
   ,FAI_COMIFAR_LISTINO_PRICE
WHERE 
	FAI_FORNITORE.CODICE_FARMACLICK= FAI_COMIFAR_LISTINO.CODICE_CLIENTE 
    AND FAI_COMIFAR_LISTINO.OID = FAI_COMIFAR_LISTINO_PRICE.OID_COMIFAR_LISTINO
	AND FAI_COMIFAR_LISTINO_PRICE.QUANTITA = 1
--UNION via via le altre tabelle delle altre fonti   

;