CREATE OR REPLACE VIEW V_FAI_LISTINI_FORNITORI 
AS 
SELECT
   'FARMACLICK'                                   FONTE
  ,FAI_FARMACLICK_FORNITORE.CODICE                CODICE_FORNITORE_FONTE
  ,FAI_FORNITORE.CODICE                           CODICE_FORNITORE
  ,FAI_FORNITORE.OID                              OID_FORNITORE
  ,NVL(LISTINO.CODICE_MINSAN, LISTINO.CODICE_EAN) CODICE
  ,LISTINO.CODICE_MINSAN                          CODICE_MINSAN  
  ,LISTINO.CODICE_EAN                             CODICE_EAN     
  ,LISTINO.DESCR_PRODOTTO                         DESCRIZIONE
  ,LISTINO.ALIQUOTA_IVA                           ALIQUOTA_IVA
  ,LISTINO.PREZ_VEND_LIST_LORDO_SC                PREZZO_LORDO_SCONTI
  ,ROUND(LISTINO.PREZ_VEND_LIST_LORDO_SC * (1 + ALIQUOTA_IVA/100)                           , 2)    PREZZO_LORDO_SCONTI_IVATO
  ,ROUND(LISTINO.PREZ_VEND_LIST_LORDO_SC * (1-SOMMA_SCONTO_1_2/100)                         , 2)    PREZZO
  ,ROUND(LISTINO.PREZ_VEND_LIST_LORDO_SC * (1 + ALIQUOTA_IVA/100) * (1-SOMMA_SCONTO_1_2/100), 2)    PREZZO_IVATO
FROM 
   FAI_FORNITORE
  ,FAI_FARMACLICK_FORNITORE 
  ,FAI_RECORD_L_LISTINO LISTINO
WHERE  
   FAI_FORNITORE.CODICE_FARMACLICK= FAI_FARMACLICK_FORNITORE.CODICE
   AND
   FAI_FARMACLICK_FORNITORE.OID = LISTINO.OID_FORNITORE
UNION
SELECT
   'COMIFAR'                                   FONTE
  ,FAI_COMIFAR_LISTINO.CODICE_CLIENTE          CODICE_FORNITORE_FONTE
  ,FAI_FORNITORE.CODICE                        CODICE_FORNITORE
  ,FAI_FORNITORE.OID                           OID_FORNITORE
  ,FAI_COMIFAR_LISTINO.CODICE_MINSAN           CODICE
  ,FAI_COMIFAR_LISTINO.CODICE_MINSAN           CODICE_MINSAN  
  ,''                                          CODICE_EAN     
  ,FAI_COMIFAR_LISTINO.NOTA_PRODOTTO           DESCRIZIONE
  ,FAI_COMIFAR_LISTINO.ALIQUOTA_IVA            ALIQUOTA_IVA
  ,FAI_COMIFAR_LISTINO.SCONTO                  PREZZO_LORDO_SCONTI
  ,NULL                                        PREZZO_LORDO_SCONTI_IVATO
  ,FAI_COMIFAR_LISTINO_PRICE.PREZZO_NETTO      PREZZO
  ,NULL                                        PREZZO_IVATO
FROM 
	FAI_FORNITORE,
    FAI_COMIFAR_LISTINO
   ,FAI_COMIFAR_LISTINO_PRICE
WHERE 
	FAI_FORNITORE.CODICE_FARMACLICK= FAI_COMIFAR_LISTINO.CODICE_CLIENTE 
    AND FAI_COMIFAR_LISTINO.OID = FAI_COMIFAR_LISTINO_PRICE.OID_COMIFAR_LISTINO
	AND FAI_COMIFAR_LISTINO_PRICE.QUANTITA = 1
--UNION via via le altre tabelle delle altre fonti   

;

CREATE OR REPLACE VIEW V_FAI_LISTINI_UPLOAD_TASKS 
AS 
SELECT
	   TASK.OID               TASK_OID
     , TASK.DESCR             TASK_DESCRIPTION
     , TASK.CSV_FILE_NAME     TASK_CSV_FILE_NAME
     , TASK.MAGAZZINO_ACRONYM TASK_MAGAZZINO_ACRONYM
     , TASK.STATUS_DESCR        TASK_STATUS_DESCR
     , TASK.STATUS_TECH_DESCR TASK_STATUS_TECH_DESCR
     , CASE WHEN COLL.OID_STATUS IS NULL THEN 1  ELSE COLL.OID_STATUS END   OID_STATUS
     , COLL.STATUS_TECH_DESCR STATUS_TECH_DESCR
     , COLL.STATUS_UPDATED_TS STATUS_UPDATED_TS
     , FIS.ACRONYM            STATUS
     , FIS.DESCR              STATUS_DESCR
     , TASK.CREATION_TS       TASK_CREATION_TS
	 
FROM FAI_UPLOAD_TASK TASK
         LEFT JOIN FAI_ORDINE_IN_COLLECTION COLL
                   ON TASK.CSV_FILE_NAME = COLL.INPUT_RESOURCE
         LEFT JOIN FAI_ITEM_STATUS FIS
                   ON COLL.OID_STATUS = FIS.OID

ORDER BY TASK.CREATION_TS

UNION
SELECT
   TASK.OID                 NULL
  ,TASK.DESCR               TASK_DESCRIPTION
  ,TASK_PROPERTY.CSV_FILE_NAME       TASK_CSV_FILE_NAME
FROM 
	FAI_GENERIC_TASK TASK,
    FAI_GENERIC_TASK_PROPERTY TASK_PROPERTY
WHERE 
	FAI_FORNITORE.CODICE_FARMACLICK= FAI_COMIFAR_LISTINO.CODICE_CLIENTE 
    AND FAI_COMIFAR_LISTINO.OID = FAI_COMIFAR_LISTINO_PRICE.OID_COMIFAR_LISTINO
	AND FAI_COMIFAR_LISTINO_PRICE.QUANTITA = 1
--UNION via via le altre tabelle delle altre fonti   

;